### ISSUE TITLE
apt-key is deprecated and scheduled for removal after ubuntu 22.04

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/metal3-dev-env#1004]
We are making use of `apt-key` for managing APT keys. This tool is deprecated and scheduled for removal after 22.04 (so we likely need to fix this before upgrading to 24.04).

References:

- [man page for apt-key](http://manpages.ubuntu.com/manpages/jammy/man8/apt-key.8.html). See the deprecation notice. There is a suggestion for how to manage the keys without apt-key.
- [the ansible module we are using](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#notes)

**Comment by Rozzii** [comment]
I think we have forgot about this one @lentzi90  let's talk

**Comment by Rozzii** [comment]
/remove-lifecycle frozen
Work has been started on this issue.

**Comment by Rozzii** [comment]
Clarification: Work has not been started but it is planned to start.
