### ISSUE TITLE
Permission denied running make

### ISSUE THREAD

**Issue by encanto-oss** [metal3-io/metal3-dev-env#1011]
suer.cert-manager.io/baremetal-operator-selfsigned-issuer created
validatingwebhookconfiguration.admissionregistration.k8s.io/baremetal-operator-validating-webhook-configuration created
~/go/src/github.com/metal3-io/baremetal-operator
+ '[' true == true ']'
+ '[' true == true ']'
+ sudo mkdir -p /opt/metal3/certs/ca/
+ cp /opt/metal3-dev-env/certs/ironic-ca.pem /opt/metal3/certs/ca/crt
cp: cannot create regular file '/opt/metal3/certs/ca/crt': Permission denied
make: *** [Makefile:10: launch_mgmt_cluster] Error 1

**Comment by Rozzii** [comment]
Have you tried this with passwordless sudo?
SeLinux config or other security tools could cause issues.
