### ISSUE TITLE
Upgrade feature test should allow upgrading to k8s 1.25.2

### ISSUE THREAD

**Issue by kashifest** [metal3-io/metal3-dev-env#1107]
Currently upgrade feature test is not upgrading to k8s 1.25.x, its still upgrading to k8s 1.24.x. We need to tackle this issue soon.

**Comment by furkatgofurov7** [comment]
@kashifest this should be completed by https://github.com/metal3-io/metal3-dev-env/pull/1108, can we close the issue?
