### ISSUE TITLE
Is there any guide how the node image is built

### ISSUE THREAD

**Issue by ydp** [metal3-io/metal3-dev-env#1150]
Hello team,

Thank for for the great project! I was wondering how to build the node image myself, not using the one hosted on https://artifactory.nordix.org/ui/native/metal3/images/k8s_v1.26.0/,  is there any guide on this? Thanks！

**Comment by furkatgofurov7** [comment]
@ydp hi!

The scripts to build the node images are hosted in this repo: https://github.com/Nordix/metal3-dev-tools aaaand sometimes things get a bit complicated when you see all the scripts for the first time 😀 

Nevertheless, here are notes how to build the image locally here: https://github.com/Nordix/metal3-dev-tools/tree/main/ci/images#building-and-testing-locally which uses the [`run_local.sh`](https://github.com/Nordix/metal3-dev-tools/blob/main/ci/images/run_local.sh) script (please skip and customize it if you do not need to upload the image to any artifactory). 

To actually build the node image (whether Ubuntu or CentOS) with all the binaries prebaked into it, check out the scripts under this folder: https://github.com/Nordix/metal3-dev-tools/tree/main/ci/scripts/image_scripts, [provision_node_image_centos.sh](https://github.com/Nordix/metal3-dev-tools/blob/main/ci/scripts/image_scripts/provision_node_image_centos.sh) or [provision_node_image_ubuntu.sh](https://github.com/Nordix/metal3-dev-tools/blob/main/ci/scripts/image_scripts/provision_node_image_ubuntu.sh). 

Let me know if you face any issues along the way and I will try to help!

**Comment by ydp** [comment]
Thank you @furkatgofurov7 so much! This is very helpful, I will try it first.
