### ISSUE TITLE
Failed to install the dev environment due to a timeout in one of the kubectl commands

### ISSUE THREAD

**Issue by shellclear** [metal3-io/metal3-dev-env#1227]
The installation process fails with the error below:

```bash
[metal3@metal3 metal3-dev-env]$ make
...
+ [[ false != true ]]
+ kubectl rollout status deployment baremetal-operator-controller-manager -n baremetal-operator-system --timeout=5m
Waiting for deployment "baremetal-operator-controller-manager" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "baremetal-operator-controller-manager" rollout to finish: 0 of 1 updated replicas are available...
error: timed out waiting for the condition
+ echo 'baremetal-operator-controller-manager deployment can not be rollout'
baremetal-operator-controller-manager deployment can not be rollout
+ exit 1
make: *** [Makefile:10: launch_mgmt_cluster] Error 1
[metal3@metal3 metal3-dev-env]$
```

This error occurs because the timeout set for the kubectl command is of  only 5 minutes, which in some cases is insufficient, especially on machines with fewer resources. The link below will take you to the mentioned command

```bash
    if ! kubectl rollout status deployment "${BMO_NAME_PREFIX}"-controller-manager -n "${IRONIC_NAMESPACE}" --timeout=5m; then
      echo "baremetal-operator-controller-manager deployment can not be rollout"
      exit 1
    fi
```
https://github.com/metal3-io/metal3-dev-env/blob/main/03_launch_mgmt_cluster.sh#L466

I got around the situation by changing the timeout value of the executed command

**Comment by shellclear** [comment]
btw, I opened a merge request to solve this issue, below the link to the pull/merge request

https://github.com/metal3-io/metal3-dev-env/pull/1228

**Comment by Rozzii** [comment]
/triage accepted
Thanks for finding and fixing this!!!!

**Comment by shellclear** [comment]
PR merged against main..

https://github.com/metal3-io/metal3-dev-env/pull/1228
