### ISSUE TITLE
minikube delete hangs after bumping to v1.31.1

### ISSUE THREAD

**Issue by kashifest** [metal3-io/metal3-dev-env#1264]
It seems like after bumping minikube to [v1.31.1](https://github.com/metal3-io/metal3-dev-env/pull/1262) tests are stuck while deleting minikube. 

One example run is here:

https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-4_e2e_integration_test_centos/104/console

**Comment by kashifest** [comment]
It seems even after the WA in https://github.com/metal3-io/metal3-dev-env/pull/1265 , there are cases where libvirt daemon is becoming unresponsive https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_e2e_feature_test_centos/192/console . This issue can be marked as a flake. There are open issues linking this to libvirt issue: https://bugzilla.redhat.com/show_bug.cgi?id=2213660 

/kind flake

**Comment by mboukhalfa** [comment]
@kashifest it this issue assigned or fixed by someone already ?

**Comment by kashifest** [comment]
This can be closed.
