### ISSUE TITLE
Applying BMH Should Be Part of the Test Setup

### ISSUE THREAD

**Issue by mboukhalfa** [metal3-io/metal3-dev-env#1383]
Currently, in the Metal³ dev-env, BMHs are applied in the `metal3` namespace and then inspected during the make process. However, when reusing CAPI tests such as `md_remediations.go`, which utilizes random namespace we are applying bmh in that namespace through the hook `PostNamespaceCreated`, it becomes evident that applying BMHs in the `metal3` namespace and then deleting them in e2e tests, only to recreate them in a different namespace, is not the most efficient approach.

To streamline the testing process and ensure alignment with evolving testing methodologies, it's recommended to update dev-env so that BMHs are applied as part of the test setup, directly in the appropriate namespace, rather than being applied by default in the `metal3` namespace as part of the make process.

**Proposed Solution:**

1. Remove the step of applying BMHs in the verify.sh script and inspecting them.
2. Update the Ansible tests under /tests to apply the BMHs from a separate file before running the tests.
3. Eliminate the part where BMHs are deleted from the metal3 namespace and instead include applying them as part of every e2e test.
4. Remove the BMH file bmhosts_crs.yaml since it will no longer be needed ([#1353](https://github.com/metal3-io/metal3-dev-env/pull/1353))

Reference: https://github.com/metal3-io/cluster-api-provider-metal3/issues/1080

**Comment by mboukhalfa** [comment]
@adilGhaffarDev I think we can close this or until we make it for all tests ?

**Comment by Rozzii** [comment]
/close
According to 2024-10-23 Community Meeting decision.
