### ISSUE TITLE
Add support for Ubuntu 24.04

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-dev-env#1430]
Ubuntu 24.04 is out since April, add support for it. At the latest we should support it when 24.04.1 is out in October.

**Comment by tuminoid** [comment]
/remove-lifecycle stale

24.04.1 is out and this can be worked on.

**Comment by elfosardo** [comment]
Is anyone already working on this? Otherwise I'm happy to take it, I'm also working on the ubuntu noble support in ironic CI https://review.opendev.org/c/openstack/ironic/+/934150

**Comment by tuminoid** [comment]
> Is anyone already working on this? Otherwise I'm happy to take it, I'm also working on the ubuntu noble support in ironic CI https://review.opendev.org/c/openstack/ironic/+/934150

AFAIK no. You're on a good roll, so please go ahead :) 

/assign @elfosardo

**Comment by tuminoid** [comment]
Btw, I'm happy to test it as I run all my tests on top of vanilla.
