### ISSUE TITLE
ipv6 provisioning doesn't work on CentOS

### ISSUE THREAD

**Issue by hardys** [metal3-io/metal3-dev-env#149]
Follow-up issue from #96 - there are two problems preventing any CentOS support for ipv6 provisioning atm:

There aren't any CentOS 8 cloud images yet in http://cloud.centos.org/centos/8/

CentOS 7 doesn't work is because the cloud images are BIOS only. FCOS and Ubuntu both have dual BIOS/UEFI images. Hopefully when CentOS 8 images come out they will be dual boot.

The deployment does currently work on RHEL8, it's not yet been tested on Ubuntu but sounds like that is expected to work.

**Comment by stbenjam** [comment]
Looks like there's CentOS 8 cloud images: http://cloud.centos.org/centos/8/x86_64/images/

When https://github.com/metal3-io/metal3-dev-env/issues/180 is resolved, we should test that we can deploy CentOS 8 w/ IPv6
