### ISSUE TITLE
zeromq installation failed

### ISSUE THREAD

**Issue by guoruijing** [metal3-io/metal3-dev-env#17]
I use centos/7 vagrant box. centos version:
[vagrant@metal3 ~]$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 

zeromq installation failed.

After the following workaround, the installation was finished:
#workaroud zeromq compatible issue
sed -i "s/zeromq/xxxxx/g" 01_install_requirements.sh
make

**Comment by russellb** [comment]
I believe this is resolved by PR #18
