### ISSUE TITLE
Move to CentOS 8

### ISSUE THREAD

**Issue by stbenjam** [metal3-io/metal3-dev-env#180]
We should move to using CentOS 8 images everywhere we can.

**Comment by elfosardo** [comment]
all of the images have PRs to convert them to Centos8, most of them are already merged, we're just missing:
https://github.com/metal3-io/ironic-image/pull/128
https://github.com/metal3-io/ironic-inspector-image/pull/37
https://github.com/metal3-io/ironic-hardware-inventory-recorder-image/pull/6

**Comment by fmuyassarov** [comment]
@stbenjam I have tried to move to CentOS8 and faced the following issues:

1.  Installation of tripleo-repos for virtualbmc fails, as it can’t get the right version for CentOS8
[tripleo-repos](https://github.com/metal3-io/metal3-dev-env/blob/dc19530d50cdeaba326e877a4f053fd44e7c6533/centos_install_requirements.sh#L50)

2.  Installation of following packages failed with yum/dnf. However those can be installed with pip3.
```
"No package python3-ironicclient available.",
"No package python3-ironic-inspector-client available.",
"No package python3-openstackclient available.",
"No package python3-virtualbmc available."
```
3. Ansible task to start firewall failing, while it works when started manually
[firewalld](https://github.com/metal3-io/metal3-dev-env/blob/e7e19fdf2832c65644edcb52993f5605a9275cf0/vm-setup/roles/firewall/tasks/firewalld.yaml#L1)

**Comment by elfosardo** [comment]
@fmuyassarov this PR #187 should fix 1, and by consequence should fix 2, since those packages are in tripleo repo.

**Comment by fmuyassarov** [comment]
@elfosardo Thanks.  I'll try meanwhile to build metal3-dev-env based on your PR

**Comment by hardys** [comment]
> Installation of tripleo-repos for virtualbmc fails, as it can’t get the right version for CentOS8
tripleo-repos

Can you clarify this problem, virtualbmc should be run in a container now?

https://github.com/metal3-io/metal3-dev-env/blob/master/02_configure_host.sh#L185

AFAIK the only dependency on the RDO repos now is the openstack/ironic python clients, so if we can agree a different way to install those (even pip) the RDO repos aren't needed at all, which is where I was headed with #157 but it needs a rebase.

**Comment by hardys** [comment]
Just to clarify I'm fine with the #187 if needed as a quick-fix, but as discussed on the PR ideally I'd like to see us break the dependency of the OS on the RDO repos and just rely on containers for everything (including the client)

**Comment by fmuyassarov** [comment]
> > Installation of tripleo-repos for virtualbmc fails, as it can’t get the right version for CentOS8
> > tripleo-repos
> 
> Can you clarify this problem, virtualbmc should be run in a container now?
> 
> https://github.com/metal3-io/metal3-dev-env/blob/master/02_configure_host.sh#L185
> 
> AFAIK the only dependency on the RDO repos now is the openstack/ironic python clients, so if we can agree a different way to install those (even pip) the RDO repos aren't needed at all, which is where I was headed with #157 but it needs a rebase.

Sorry for late reply,
Right, virtualbmc is running in a container, and I believe we don't need the following lines [here](https://github.com/metal3-io/metal3-dev-env/blob/645da0459a89a368f73e2e8a3d7e4504458295ed/centos_install_requirements.sh#L50) , no?

**Comment by hardys** [comment]
See #223 which adds support for CentOS8 hosts without any dependency on the RDO repos

**Comment by hardys** [comment]
@maelk now https://github.com/metal3-io/metal3-dev-env/pull/223 landed, and all the images moved to centos8 (@elfosardo) - the last remaining item is moving the centos CI to use centos8, then we can deprecate centos7 support?

How will we go about moving the integration CI to centos8?

**Comment by maelk** [comment]
That should be pretty straightforward. We just need to change the image build job to use another base. I'll put the patchset together now.

**Comment by maelk** [comment]
The image is now centos8 ! I'll trigger the tests somewhere to check everything goes fine.

**Comment by fmuyassarov** [comment]
Should this issue be closed now? or shall we wait until we switch to using centos-8 cloud image for workers/controlplane ?

**Comment by fmuyassarov** [comment]
/cc @hardys 
/cc @maelk 
/cc @elfosardo 

Should this issue be closed now? or shall we wait until we switch to using centos-8 cloud image for workers/controlplane as well ? If you think that we should wait until we start using centos-8 cloud image for workers/conrolplane as well I have a WIP [PR#257](https://github.com/metal3-io/metal3-dev-env/pull/257) for that.

**Comment by maelk** [comment]
I think we can wait and keep this open until everything is moved to CentOS8

**Comment by alosadagrande** [comment]
Related issue #263 when creating control-plane VM in the target cluster.

**Comment by fmuyassarov** [comment]
@maelk is there anything else left related to this issue?

**Comment by maelk** [comment]
I don't think so 
/close
