### ISSUE TITLE
Installing metal3 behind an http proxy

### ISSUE THREAD

**Issue by aschiefe** [metal3-io/metal3-dev-env#195]
By default this code base does not support corporate proxy settings

Specifically with the proxy issues and ubuntu 18.04 the ubuntu_install_requirements.sh does not appear to honor the proxy configurations for several things:
1.  line 38 sudo add-apt-repository -y ppa:projectatomic/ppa
2.  line 40 add-apt-repository -y ppa:longsleep/golang-backports
3.  line 68 sudo pip3 install

These issues can be resolved by applying a sudo -E so that it picks up the environment settings or informing the pip install that there is a proxy setting however the deployment of the metal3-baremetal-operator does not pick up the environment and will fail every time pulling in the agents it's attempting to install ignoring the environment settings:

```
ubuntu@virtual-airship:~/metal3-dev-env$ kubectl logs metal3-baremetal-operator-5cbbd7b87d-kvcbx --previous -n metal3 ironic-ipa-downloader
+ export http_proxy=
+ http_proxy=
+ export https_proxy=
+ https_proxy=
+ SNAP=current-tripleo
+ IPA_BASEURI=https://images.rdoproject.org/train/rdo_trunk/current-tripleo/
+ FILENAME=ironic-python-agent
+ FILENAME_EXT=.tar
+ FFILENAME=ironic-python-agent.tar
+ mkdir -p /shared/html/images /shared/tmp
+ cd /shared/html/images
++ mktemp -d -p /shared/tmp
+ TMPDIR=/shared/tmp/tmp.XQ3D6VInff
+ ls -l
total 4
-rw-r--r-- 1 root root 306 Jan 22 22:31 ironic-python-agent.tar.headers
+ '[' -n http://172.22.0.1/images -a '!' -e ironic-python-agent.tar.headers ']'
+ '[' -e ironic-python-agent.tar.headers ']'
++ awk '/ETag:/ {print $2}' ironic-python-agent.tar.headers
++ tr -d '\r'
+ ETAG='"18632000-59c951f5a7ab6"'
+ cd /shared/tmp/tmp.XQ3D6VInff
+ curl -g --verbose --dump-header ironic-python-agent.tar.headers -O https://images.rdoproject.org/train/rdo_trunk/current-tripleo//ironic-python-agent.tar --header 'If-None-Match: "18632000-59c951f5a7ab6"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 38.145.33.168...
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0* connect to 38.145.33.168 port 443 failed: Connection timed out
* Failed to connect to images.rdoproject.org port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to images.rdoproject.org port 443: Connection timed out
ubuntu@virtual-airship:~/metal3-dev-env$
```

**Comment by stbenjam** [comment]
Were you able to get this to work? I know there were some discussions on the mailing list about how to make this work.

**Comment by aschiefe** [comment]
I have gotten past this issue, there's still some lingering issues because I haven't gotten it all the way through the verification yet.  I will hopefully get back on this later this week and can supply a patch if I get it figured out.

**Comment by stbenjam** [comment]
@aschiefe Any update on this? Thanks!

**Comment by aschiefe** [comment]
I'm still unable to get a successful run all the way through verification.  I haven't dug into it much since my last attempt, I'll try again today.  It's possible I don't have the right setup to accomplish a test install.

**Comment by stbenjam** [comment]
Any update on this? Thanks

**Comment by stbenjam** [comment]
Going to close this, please re-open if you have some new information

/close

**Comment by l4z41** [comment]
If the `http_proxy` variable is set in `/etc/environment` and not via `export http_proxy=` then it will respect that for `sudo add-apt-repository -y ppa:projectatomic/ppa`.

For the _ironic-ipa-downloader_ I got it to work with simply editing the `function kustomize_overlay_bmo()` in `03_launch_mgmt_cluster.sh` with adding the environment variables manually to `ironic-bmo-configmap`.

This could be pulled from system environment if set. It would solve this particular problem, but not the security implications of directly loading additional code from `https://images.rdoproject.org/train/rdo_trunk/current-tripleo/`.

**Comment by l4z41** [comment]
Additionally `no_proxy` is not set, so there will be problems with ip ranges and hostname `minikube`. Please embed further third party code as submodule or directly into image.

/open
