### ISSUE TITLE
Default CAPI_VERSION is set to `v1alpha1`

### ISSUE THREAD

**Issue by e-minguez** [metal3-io/metal3-dev-env#200]
https://github.com/metal3-io/metal3-dev-env/blob/master/lib/common.sh#L88
https://github.com/metal3-io/metal3-dev-env/blob/master/config_example.sh#L87

According to https://metal3.io/try-it.html#setup the default value should be `v1alpha2`

**Comment by maelk** [comment]
We need to update the try-it docs

**Comment by fmuyassarov** [comment]
@e-minguez During the last community meeting it was decided that default CAPI version should be switched to v1alpha3. As such,  I have opened couple of PRs [#62](https://github.com/metal3-io/project-infra/pull/62), [#155](https://github.com/metal3-io/metal3-io.github.io/pull/155) to update docs with regard to this change.
