### ISSUE TITLE
Development environment on Ubuntu 

### ISSUE THREAD

**Issue by namnx228** [metal3-io/metal3-dev-env#21]
I'm thinking about a dev-env which can run on Ubuntu, so we will have more OS choices. Besides, this dev-env should be in Ansible playbooks only, not playbooks call bash-script and bash-scripts call playbook, so it will be easier to maintain and add more feature to it.
__What do you think about this ?__

**Comment by hardys** [comment]
Sounds reasonable to me, AFAIK this should work fairly easily on any environment that supports libvirt, and I agree refactoring some of the bash scripts into the ansible roles would be helpful (although perhaps that should be tracked as a separate task) - I made a similar comment on https://github.com/metal3-io/metal3-dev-env/pull/19 and plan to spend some time on that unless anyone does it before I get to it :)

**Comment by namnx228** [comment]
> Sounds reasonable to me, AFAIK this should work fairly easily on any environment that supports libvirt, and I agree refactoring some of the bash scripts into the ansible roles would be helpful (although perhaps that should be tracked as a separate task) - I made a similar comment on #19 and plan to spend some time on that unless anyone does it before I get to it :)

You're right, the refactoring task may be separated from the task that makes the dev-env running on Ubuntu. If there is nobody taking care of this task (Ubuntu task) right now, I will do it.

**Comment by russellb** [comment]
Ubuntu support sounds great.

I'm more neutral on the ansible part, but I'm OK with it.

**Comment by namnx228** [comment]
Hi,
I have made some changes and the dev-env now can run on my Ubuntu local machine. But there are still some problems with `bridges`. If we want to configure two `bridges` and make them permanently, the way to do it is different between Ubuntu 18.04 and lower version. Ubuntu 18.04 uses `Netplan` to do the all networking stuffs, including adding `bridges`, but lower versions of Ubuntu use `/etc/network/interfaces` to do that. However, it is the same if we just add `bridges` temporarily using `brctl`. 
However, the temporary bridges will disappear after we restart our machines. 

So, what do you think ? Should we add bridges temporarily on Ubuntu, or permanently ?

**Comment by hardys** [comment]
I think using brctl is fine - particularly if there are some manual/script steps which can be re-run to revive an environment after an unexpected host reboot?

**Comment by namnx228** [comment]
> I think using brctl is fine - particularly if there are some manual/script steps which can be re-run to revive an environment after an unexpected host reboot?

Yes, if i don't go wrong, each time we restart  the host, we need to re-run 2 scripts `02_configure_host.sh` and `03_launch_mgmt_cluster.sh` if we want the dev-env works properly. So, I think `brctl` can be put into script `02_configure_host.sh` so it can be re-executed after the host reboots.
