### ISSUE TITLE
Support for chroot based environment

### ISSUE THREAD

**Issue by pablochacin** [metal3-io/metal3-dev-env#22]
This issue follows the progress  in installing the development environment in a chroot based Centos7 environment on top of Opensuse. One important objective was to use the libvirt already running in the host machine

There are some minor hacks needed and some unsolved issues. 

## Hacks
* This is not specific to `metal3` but in order to make `yum` run in chroot, it is necessary to bind mount `/proc` and `/dev` directories into the chroot environment [1]
* The installation script checks the filesystem using the output from the command `df /`. In a chroot environment, the result is not reliable. Even following the generally suggested solution of making `/etc/mtab` a symbolic link to `/proc/mounts` in the chroot environment, at some point it stopped working and I had to skip this check.
* Podman doesn't work on top of an `xfs` file system. I had to install `fuse-overlayfs` and change podman's configuration to use it as storage driver. This process itself is tricky as there seems not to be packages for Centos and I had to install from sources. 
* Podam requires to access `/run/systemd/private` socket. The directory `/run/systemd` must be bind mounted in the chroot environment 
* In order to use the host's libvirt, the directory `/opt/run/libvirt` must be mounted in the chroot environment
* The directory `/opt/metal3-dev-env/pool` must be created in the host machine because is used when creating the `ooq_pool` storage pool
* I had to manually modify the the `libvirt_uri` in `vm-setup/roles/virtbmc/tasks/setup_tasks.yml` to use `qemu:///system` instead of the url `qemu+ssh:///vbmc_address` 

## Issues
* [ ] At some point in the installation process, there was a problem because the `provisioing` network was already created. I had to clean up the host with the `host_cleanup.sh` script and start over again. 
* [ ] The `virtualbmc` service is not started because the setup process uses `systemd` to start it and this is not supported under chroot. This is the more likely root cause of the issue below. 
* [ ] The commands `vbmc add <role>_0 --port 6230 --libvirt-uri qemu:///system` for `<role>`="`master`"|"`worker`" fails with the error `Server at 50891 may be dead, will not try to revive it`. There is however, `vbmc` process listening at this port. This seem related to the next issue
* [ ] The `vbmc` keeps restarting as shown in `/etc/log/virtualbmc/virtualbmc.log`:

```
DEBUG VirtualBMC [-] Server at 50891 connection error: Server response timed out
DEBUG VirtualBMC [-] Attempting to start `vbmcd` behind the scenes. Consider configuring your system to manage `vbmcd` via systemd. Automatic `vbmcd` start up will be removed in the future releases!
ERROR VirtualBMC [-] Control server error: Address already in use
```
* [ ] The master_0 and worker_0 domains are created, but remains `shut off`. The can be started manually, but I cannot assert if they are actually running. Attaching to the console doesn't show any output.

## References
[1] https://serverfault.com/questions/866294/error-failed-to-initialize-nss-library

**Comment by pablochacin** [comment]
The path for volume storage is defined in `vm-setup/roles/common/defaults/main.yml':
```
libvirt_volume_path: "{{ working_dir }}/pool"
```

**Comment by pablochacin** [comment]
The uri to `libvirt` is defined in `vm-setup/roles/common/defaults/main.yml`:
```
libvirt_uri: qemu:///system
```
However, an url was used instead. Need to check where this default is override.

**Comment by hardys** [comment]
I wonder would it be easier to either switch to installing python-virtualbmc from source (or maybe pip --user?) - alternatively perhaps we could instead build a container image?

The main dependency here is libvirt, so I'm thinking with some work we could potentially make this setup much more portable?

**Comment by pablochacin** [comment]
> alternatively perhaps we could build a container image
This was my first attempt, but there were issues with running podman inside a container.

**Comment by pablochacin** [comment]
Here is where the actual uri to qemu is set for `vbmc`:
https://github.com/metal3-io/metal3-dev-env/blob/24c0d596b89bca7fee899186cb82f0548c4f8b2d/vm-setup/roles/virtbmc/tasks/setup_tasks.yml#L43-L53

**Comment by pablochacin** [comment]
Realized ironic pods were not running because  `podman` failed when creating a pod:

>Error: unable to create pod: unable to create pod cgroup for pod 0e71e2bcca59c153b3de97d77e50ff2f6d1f830bcda0090f8e5feb1384cee951: error creating cgroup machine.slice/machine-libpod_pod_0e71e2bcca59c153b3de97d77e50ff2f6d1f830bcda0090f8e5feb1384cee951.slice: dial unix /run/systemd/private: connect: no such file or directory

The directory `/run/systemd` must be mounted in the chroot environment

**Comment by pablochacin** [comment]
The problem is apparently that the `virtuabmc` service is not started because the setup process uses `systemd` which is not supported under chroot.

**Comment by pablochacin** [comment]
> The main dependency here is libvirt, so I'm thinking with some work we could potentially make this setup much more portable?

**Comment by hardys** [comment]
Ack, thanks for looking into this - I did indeed mean run the virtualbmc service in a container, or we could probably run it without systemd as IIRC that's a packaging thing, instead we could install it either via pip or from source in a virtualenv ref https://docs.openstack.org/virtualbmc/latest/install/index.html

If we do add such an option it'd be nice to ensure there's a choice to install either the packaged or from-source version.

**Comment by pablochacin** [comment]
I can confirm that starting the `/usr/bin/vbmcd` manually works. `vbmc` can connect to the server and interface with vms using `libvirt` running in the host.

**Comment by dhellmann** [comment]
I wonder if it would be easier to just teach the scripts about openSUSE?

**Comment by pablochacin** [comment]
I took a look but installation requires a significant amount of packages and IIRC some where not available. More recently I learned about [Footloose](https://github.com/weaveworks/footloose) containers hat support systremd and podman. I would try to install on top of it.

**Comment by pablochacin** [comment]
That said, it definitely worth porting the scripts to opensuse.

**Comment by russellb** [comment]
Let’s figure out what packages aren’t available. Some are not strictly
needed. If they are required, we can add installation from source.

Sent from mobile device

On Aug 24, 2019, at 5:52 AM, pablochacin <notifications@github.com> wrote:

That said, it definitely worth porting the scripts to opensuse.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/metal3-io/metal3-dev-env/issues/22?email_source=notifications&email_token=AACLQCRBY3KBRDQKDMWOR3TQGEAHNA5CNFSM4H4DEMAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5B46CI#issuecomment-524537609>,
or mute the thread

**Comment by russellb** [comment]
I need to finish adding rhel 8 support here. I bet we would share some of the source installs.

**Comment by hardys** [comment]
@pablochacin virtualbmc is now run in a container, so should we close this issue?

I'm unclear if that was the only problem you were aiming to resolve via the use of a chroot - in general I think running components isolated in containers is probably a more flexible solution to dependency problems than a chroot?

**Comment by pablochacin** [comment]
@hardys IIRC the problem was that the ansible scripts use systemd which is not available in containers without some additional work. But if everything is now in a container, the support for chroot is not required.

**Comment by hardys** [comment]
> @hardys IIRC the problem was that the ansible scripts use systemd which is not available in containers without some additional work. But if everything is now in a container, the support for chroot is not required.

all virtualbmc services now run in a container so I think we can close this, feel free to reopen if that proves not to be the case - thanks!
