### ISSUE TITLE
Deployment fails on new CentOS7 host due to firewall disabled

### ISSUE THREAD

**Issue by hardys** [metal3-io/metal3-dev-env#221]
On a new minimal CentOS box we see this error from 01_prepare_host in configure_minikube:

```
X Unable to start VM. Please investigate and run 'minikube delete' if possible: create: Error creating machine: Error in driver during machine creation: creating network: creating network minikube-net: virError(Code=89, Domain=47, Message='The name org.fedoraproject.FirewallD1 was not provided by any .service files')
```

There seem to be two problems - it's assuming FirewallD but we assume iptables on CentoOS7 - AFAICS firewalld is the correct choice on 7.7 though:

```
$ sudo systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

Feb 12 09:39:23 localhost.localdomain systemd[1]: Starting firewalld - dynamic firewall daemon...
Feb 12 09:39:23 localhost.localdomain systemd[1]: Started firewalld - dynamic firewall daemon.
Feb 12 11:41:14 localhost.localdomain systemd[1]: Stopping firewalld - dynamic firewall daemon...
Feb 12 11:41:15 localhost.localdomain systemd[1]: Stopped firewalld - dynamic firewall daemon.
$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```

The second issue is we enable the firewall in `02_configure_host.sh` which is too late since the error above happens during `01_prepare_host.sh` on a freshly installed box

**Comment by maelk** [comment]
we could remove the minikube setup from 01_prepare_host . It does not bring any value anymore since we do not bake it in CI images anymore. That would solve the second issue, plus some problems that were raised in other issues here.

**Comment by hardys** [comment]
Ok so I'm not sure we can use firewalld as it shows an error like:

```
org.fedoraproject.FirewallD1.Exception: INVALID_ZONE: libvirt
```

It seems that the centos7 libvirt/firewalld default configuration differs from RHEL/CentOS8.

**Comment by hardys** [comment]
Hmm I just re-tested from scratch with a freshly installed CentOS install and couldn't reproduce which is strange, closing this and will reopen if I figure out a reproducer

**Comment by hardys** [comment]
Actually this looks like a duplicate of https://github.com/metal3-io/metal3-dev-env/issues/199 - I suspect my second test worked because I did an extra reboot and this restarted libvirt (although I thought I did try restarting that the first time, maybe I'm mistaken)
