### ISSUE TITLE
run make with vlapha1, throws  No rule to make target `manifests'.  Stop

### ISSUE THREAD

**Issue by aneeshkp** [metal3-io/metal3-dev-env#222]
Running make with the following config  thorws an error `No rule to make target `manifests'.  Stop`
config_$USER
export BMOBRANCH="master"
export BMO_RUN_LOCAL=true
export CAPBM_RUN_LOCAL=ture
export CAPBMBRANCH="master"
#default v1alpha1 
#export CAPI_VERSION=v1alpha1

[script link ](https://github.com/metal3-io/metal3-dev-env/blob/master/03_launch_mgmt_cluster.sh#L203)

**Comment by stbenjam** [comment]
It looks like you're using the wrong branches - if you want to deploy with v1alpha1, change CAPBM branch to be v1alpha1, otherwise use version v1alpha3.

**Comment by stbenjam** [comment]
Please re-open if you're still having issues, thanks!

/close
