### ISSUE TITLE
Minikube is unstable

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-dev-env#232]
Sometimes when running the deployment, specially in CI, Minikube crashes, and the api server is unreachable. This is usually visible in the logs as : 

`Unable to connect to the server: net/http: TLS handshake timeout`
or
`Unable to connect to the server: dial tcp 192.168.39.179:8443: connect: no route to host`

We should investigate this issue to figure out if the problem is from the way we use it (for example cause a kernel panic) or if there is an issue with Minikube itself (far less probable). Then we would be able to fix what we do wrong to fix this issue. I would say the reproducing rate (in CI) is around 25%. The crashes always happen at intensive phases (introspection or provisioning). More info needed.

**Comment by alosadagrande** [comment]
I can say that I increased CPU and memory of the minikube VM in order to check if that was the culprit. However, same behavior as explained in the issue.

**Comment by maelk** [comment]
This type of problems have not been seen for a while now. closing for now 
/close
