### ISSUE TITLE
Add a clusterctl based deployment method

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-dev-env#249]
Now that CAPI v1alpha3 is released, we should add a clusterctl based deployment to validate the integration. 

What needs to be done:

- download clusterctl
- run init command instead of deploying CAPM3
- run config command to create the cluster instead of using our own template, with the proper variables in place.

There could be a switch to select which deployment method should be used.

**Comment by maelk** [comment]
@mikkosest please add a reference ("Fixes ...") in your metal3-dev-env PR that introduces clusterctl

**Comment by fmuyassarov** [comment]
@maelk @mikkosest should this issue be closed now?

**Comment by maelk** [comment]
yes, that was implemented, thanks @fmuyassarov 
/close
