### ISSUE TITLE
Failed to host deprovisioning 

### ISSUE THREAD

**Issue by jan-est** [metal3-io/metal3-dev-env#26]
Hi,

I ran into problem with host deprovisioning. After creating machine with `create_machine.sh` and deleting machine object with: `kubectl delete machine centos -n metal3`. The hosts provisioning status is like this.
```sh
NAME       STATUS   PROVISIONING STATUS                       
master-0   OK       externally provisioned             
```
When running: 
`kubectl logs -n metal3 pod/cluster-api-provider-baremetal-controller-manager-0 -c manager`
Logs shows: `2019/07/02 08:06:44 Deleting machine centos` and it is in loop and never finishing the delete.

It seems that controller is unable to delete that machine object. `kubectl get machine -n metal3` still shows centos machine object. 

I am using version CentOS 7 and version `3.10.0-957.21.3.el7.x86_64`. Virtual machine is KVM with `libvirtd (libvirt) 4.0.0`.

Does anyone have the same problem or workaround with this issue?

**Comment by karmab** [comment]
i think it s the correct behaviour.
Deleting the machine removes its linking with one of the baremetalhost objects.
to actually delete the baremetalhost you would do something like
```
kubectl delete baremetalhost master-0 -n metal3
```

**Comment by jan-est** [comment]
But I would not want to delete the actual baremetalhost, because I would like to use it again in any upcoming provisioning. If the state of the machine is `externally provisioned` it does not allow me to do another provisioning.

**Comment by russellb** [comment]
This is a bug.  As you suggest @jan-est , the host should return to a state where it's available for provisioning again.

**Comment by mikkosest** [comment]
Would it help if   setting `consumerRef = nil` would be allowed also `StateProvisioning` and `StateProvisioned` -states in `Delete` method in `actuator.go` ?

**Comment by jan-est** [comment]
@russellb good to know that this was not an issue with my local environment. @mikkosest I am not that familiar with the architecture of the metal3 but I was thinking the same thing that `consumerRef` needs to be deleted. I test editing my `master-0` yaml and deleted the `consumerRef` manually and that did the trick and deleted the machine object as well. 

But I think we can assume that this issue is noticed and will be fixed soon.

**Comment by russellb** [comment]
@mikkosest The code you're referring to came from https://github.com/metal3-io/cluster-api-provider-baremetal/pull/86 by @zaneb.  We now see the code clear the image, but delay clearing the consumerref field.

It appears the intention here was to wait for deprovisioning to complete before allowing Machine deletion to complete.  When you run `kubectl delete machine centos -n metal3`, you should see that command hanging while this occurs.

Once we have the image cleared, instead of deprovisioning, the baremetal-operator then considers the host to be externally provisioned.  Setting the consderRef and not the image is how that is indicated, so I'm honestly not sure how these changes ever worked properly?  I'll ping @zaneb to discuss

**Comment by russellb** [comment]
While we work out a proper fix for this, as discussed, manually clearing the `ConsumerRef` field is a good workaround.

Thanks again for the report!

**Comment by jan-est** [comment]
@russellb thanks for the info!

**Comment by zaneb** [comment]
metal3-io/cluster-api-provider-baremetal#97 will at least allow you to delete the Machine.

**Comment by kashifest** [comment]
@zaneb @russellb I have tested machine deletion and its working. Great Job! One question though, what is the desired state of the baremetal host after de-provisioning with regards to ```'Online'``` state. When I do machine deletion it makes the host ready but keeps it offline (```'Online'=false```) however when I am directly provisioning and then de-provisioning it returns the host to ready state while keeping it ```'Online'=true```.

**Comment by russellb** [comment]
If you directly provision and de-provision, it probably makes sense to set `online: false` there, too.  This affects whether the host is left powered on or off after deprovisioning is complete.  In most cases, I'd expect you want the host powered off, `online: false`.

**Comment by russellb** [comment]
I believe this is fully resolved now, so closing
