### ISSUE TITLE
Failed to run a custom cluster-api-provider-baremetal

### ISSUE THREAD

**Issue by kashifest** [metal3-io/metal3-dev-env#28]
Hi,

I am trying to follow the steps mentioned in ```README``` file  to run a custom ```cluster-api-provider-baremetal``` from local repositories but the ```make run``` is stuck after the following :

```
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run ./cmd/manager/main.go
{"level":"info","ts":1562319542.715248,"logger":"baremetal-controller-manager","msg":"Found API group metal3.io/v1alpha1"}
{"level":"info","ts":1562319542.7608466,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"machine-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1562319542.7609959,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"machine-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1562319542.8617175,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"machine-controller"}
{"level":"info","ts":1562319542.9623592,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"machine-controller","worker count":1}
```

The **initial guess** is that the process stucks  during Reconcilation . (Code refers to ```/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.0.0-20190124235917-12d98582e729/pkg/internal/controller/controller.go ```).

Has anyone else faced the  same issue? Am I doing something wrong?

I am using CentOS 7 - 3.10.0-957.21.3.el7.x86_64 and libvirtd (libvirt) 4.5.0 

BR
Kashif

**Comment by russellb** [comment]
Thanks for the report.

This is actually the expected behavior. `make run` runs the component in the foreground so that you can follow the log output in the terminal and quickly kill and restart as needed.  You will need to interact with the cluster from another terminal.

Let me know if you have any other questions about this!

**Comment by kashifest** [comment]
Thanks @russellb.

Indeed you are right. Since, I am new to this environment, I still have one more question.

As mentioned, in my report, I followed the steps mentioned in ```README```. At first, I scaled down the custom Machine controller manager first using the following command

```kubectl scale statefulset cluster-api-provider-baremetal-controller-manager -n metal3 --replicas=0```.

I added few lines of log prints in my local ```cluster-api-provider-baremetal-controller-manager``` repository(in ```actuator .go```) and did the ```make run```. And then when I made changes in the cluster (I was trying to delete a machine object), I saw the new log prints in the console. 

However, what I expected is that ```make run``` will scale up with the newly compiled ```cluster-api-provider-baremetal-controller-manager``` and that shall be reflected when I list the pods. Which is not the case here. So, where is the newly compiled ```cluster-api-provider-baremetal-controller-manager``` running since I cannot see this when I list the pods in the cluster ? 

Thanks in advance.
Kashif
 
> Thanks for the report.
> 
> This is actually the expected behavior. `make run` runs the component in the foreground so that you can follow the log output in the terminal and quickly kill and restart as needed. You will need to interact with the cluster from another terminal.
> 
> Let me know if you have any other questions about this!

**Comment by russellb** [comment]
When you use `make run`, you are no longer running the component in the cluster, so you won't see it when you list pods.  To run a custom image that way, you'd have to build a custom image, push it to a container registry, edit the image in the appropriate manifest under the `config/` directory, and then run `make deploy`.  It's a lot easier to test custom changes with `make run`, just at the expense of it no longer running in the cluster.

**Comment by russellb** [comment]
(sorry, didn't mean to click close)

**Comment by kashifest** [comment]
Thanks @russellb. This is clear now.
