### ISSUE TITLE
CentOS target cluster deployment fails

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-dev-env#287]
https://github.com/metal3-io/metal3-dev-env/pull/273 broke the CentOS deployment of a CAPI v1alpha3 cluster. It now fails with : 

```
systemctl enable --now docker keepalived kubelet
Failed to enable unit: Unit file /etc/systemd/system/kubelet.service is masked.
```

/assign @Xenwar

**Comment by Xenwar** [comment]
Tested it on Metal3-dev-env, and was able successfully deploy a control plane. 
env:
```
export CONTAINER_RUNTIME=docker
export DEFAULT_HOSTS_MEMORY=4096
export IMAGE_OS=Ubuntu
export CAPI_VERSION=v1alpha3
```

output
```

  kubeadm join 192.168.111.249:6443 --token ypv7ge.24qjykqza2v9sujz \
    --discovery-token-ca-cert-hash sha256:bd4c472ffd5697f90e991fcee623300acd80bae7f0c5feb9004aeda18907a9fd \
    --control-plane 

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 192.168.111.249:6443 --token ypv7ge.24qjykqza2v9sujz \
    --discovery-token-ca-cert-hash sha256:bd4c472ffd5697f90e991fcee623300acd80bae7f0c5feb9004aeda18907a9fd 
Cloud-init v. 18.5 running 'modules:final' at Wed, 08 Apr 2020 04:40:09 +0000. Up 18.15 seconds.
Cloud-init v. 18.5 finished at Wed, 08 Apr 2020 04:44:49 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/sda2].  Up 297.83 `seconds`
^C
[centos@node-1 ~]$ 
[centos@node-1 ~]$   mkdir -p $HOME/.kube
[centos@node-1 ~]$   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
cp: overwrite '/home/centos/.kube/config'? 
[centos@node-1 ~]$ kubectl get pods
No resources found in default namespace.
[centos@node-1 ~]$ 

```

**Comment by Xenwar** [comment]
And, if #273 has broken the Centos deployment, why is that the CI tests did not catch it ?

**Comment by maelk** [comment]
The CI does not test the CentOS deployment. It tests an Ubuntu deployment on a CentOS metal3-dev-env machine. So the only way to test a CentOS deployment is manually. Maybe we should make it so that when we run a centos test, we use a 32GB machine and deploy CentOS target cluster.

**Comment by maelk** [comment]
Here is a PR to introduce CentOS tests on the CI : https://github.com/metal3-io/project-infra/pull/72

**Comment by Xenwar** [comment]
> Here is a PR to introduce CentOS tests on the CI : [metal3-io/project-infra#72](https://github.com/metal3-io/project-infra/pull/72)

Thanks.
please change the description as well. As was indicated in the output, #273 did not cause the deployment failure.

**Comment by maelk** [comment]
This seems to have been a case-specific failure
