### ISSUE TITLE
Broken v1a2 deployment scripts 

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-dev-env#288]
The v1alpha2 scripts to provision target clusters are broken both for Ubuntu and Centos, they should be removed, in the templates of the ansible role and the deployment of v1alpha2 should also be removed.

**Comment by stbenjam** [comment]
Should be addressed by https://github.com/metal3-io/metal3-dev-env/pull/292

**Comment by fmuyassarov** [comment]
@maelk should it be closed?

**Comment by maelk** [comment]
yes,
/close
