### ISSUE TITLE
metal3 deployment on Centos7.7 fails

### ISSUE THREAD

**Issue by hroyrh** [metal3-io/metal3-dev-env#295]
When I tried to deploy metal3 on Centos7.7, it first gave an error saying - dnf is missing. After installing dnf and retrying I am getting this error :
```
++ [[ centos7 == \c\e\n\t\o\s\7 ]]
++ sudo dnf -y install python-pip
Last metadata expiration check: 0:00:32 ago
No match for argument: python-pip
Error: Unable to find a match: python-pip
make: *** [install_requirements] Error 1
```
If Centos 7.7 is no longer supported, please mention that in the documentation.

**Comment by codificat** [comment]
Related: metal3-io/metal3-io.github.io#173 is about updating the try-it document in the website to switch from CentOS 7 to 8

**Comment by codificat** [comment]
@hroyrh the doc was updated, does it look ok now? If so feel free to close the issue, thanks.

**Comment by hroyrh** [comment]
Yes, it looks good.
