### ISSUE TITLE
Add cloud init log out put 

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/metal3-dev-env#296]
In the CI, some jobs are failing and the output does not reveal much information. 
This [PR](281) is a case in point. It was failing due to missing binaries and the outputs did not show that. We were required to login to the provisioned machines and get the logs. 

It would be good the content of ```/var/log/cloud-init-output.log``` is also shown at the end as it would make pin pointing errors easy.

**Comment by maelk** [comment]
why was this assigned to me ? I don't have bandwidth to work on this for now.

**Comment by Xenwar** [comment]
Manually, it could be done like this.
`ssh USERNAME@SERVER_IP cat /var/log/cloud-init-output.log`

This could be done from bash or ansible.

**Comment by fmuyassarov** [comment]
Maybe it can be done with `sudo virsh console VM_NAME` to see cloud-init execution on the fly.
Example output:

=======================================================================
[  248.960289] cloud-init[1559]: Upgraded:
[  248.963800] cloud-init[1559]:   cloud-init-18.5-7.el8_1.1.noarch
[  248.965885] cloud-init[1559]:   qemu-guest-agent-15:2.12.0-88.module_el8.1.0+297+df420408.3.x86_64
[  248.969792] cloud-init[1559]:   NetworkManager-1:1.20.0-5.el8_1.x86_64
[  248.972278] cloud-init[1559]:   NetworkManager-libnm-1:1.20.0-5.el8_1.x86_64
[  248.974230] cloud-init[1559]:   NetworkManager-team-1:1.20.0-5.el8_1.x86_64
[  248.974298] cloud-init[1559]:   NetworkManager-tui-1:1.20.0-5.el8_1.x86_64
[  248.977091] cloud-init[1559]:   audit-3.0-0.13.20190507gitf58ec40.el8.x86_64
[  248.979131] cloud-init[1559]:   audit-libs-3.0-0.13.20190507gitf58ec40.el8.x86_64
[  248.980512] cloud-init[1559]:   centos-gpg-keys-8.1-1.1911.0.9.el8.noarch
[  248.982548] cloud-init[1559]:   centos-release-8.1-1.1911.0.9.el8.x86_64
[  248.984594] cloud-init[1559]:   centos-repos-8.1-1.1911.0.9.el8.x86_64
[  248.986432] cloud-init[1559]:   coreutils-8.30-6.el8_1.1.x86_64
[  248.990217] cloud-init[1559]:   coreutils-common-8.30-6.el8_1.1.x86_64
[  248.994264] cloud-init[1559]:   glibc-2.28-72.el8_1.1.x86_64
[  249.004877] cloud-init[1559]:   glibc-all-langpacks-2.28-72.el8_1.1.x86_64
[  249.022085] cloud-init[1559]:   glibc-common-2.28-72.el8_1.1.x86_64
[  249.024163] cloud-init[1559]:   grub2-common-1:2.02-78.el8_1.1.noarch
[  249.026204] cloud-init[1559]:   grub2-pc-1:2.02-78.el8_1.1.x86_64
[  249.028443] cloud-init[1559]:   grub2-pc-modules-1:2.02-78.el8_1.1.noarch
[  249.030655] cloud-init[1559]:   grub2-tools-1:2.02-78.el8_1.1.x86_64
[  249.042350] cloud-init[1559]:   grub2-tools-extra-1:2.02-78.el8_1.1.x86_64
[  249.051146] cloud-init[1559]:   grub2-tools-minimal-1:2.02-78.el8_1.1.x86_64
[  249.058153] cloud-init[1559]:   kernel-tools-4.18.0-147.8.1.el8_1.x86_64
[  249.080577] cloud-init[1559]:   kernel-tools-libs-4.18.0-147.8.1.el8_1.x86_64
[  249.088468] cloud-init[1559]:   kexec-tools-2.0.19-12.el8_1.2.x86_64
[  249.093733] cloud-init[1559]:   libarchive-3.3.2-8.el8_1.x86_64
[  249.098135] cloud-init[1559]:   libsss_autofs-2.2.0-19.el8_1.1.x86_64
[  249.100561] cloud-init[1559]:   libsss_certmap-2.2.0-19.el8_1.1.x86_64
[  249.108541] cloud-init[1559]:   libsss_idmap-2.2.0-19.el8_1.1.x86_64
[  249.110723] cloud-init[1559]:   libsss_nss_idmap-2.2.0-19.el8_1.1.x86_64
[  249.118855] cloud-init[1559]:   libsss_sudo-2.2.0-19.el8_1.1.x86_64
[  249.125736] cloud-init[1559]:   openldap-2.4.46-11.el8_1.x86_64
[  249.130150] cloud-init[1559]:   openssh-8.0p1-4.el8_1.x86_64
[  249.143852] cloud-init[1559]:   openssh-clients-8.0p1-4.el8_1.x86_64
[  249.146210] cloud-init[1559]:   openssh-server-8.0p1-4.el8_1.x86_64
[  249.153723] cloud-init[1559]:   openssl-1:1.1.1c-2.el8_1.1.x86_64
[  249.174876] cloud-init[1559]:   openssl-libs-1:1.1.1c-2.el8_1.1.x86_64
[  249.177304] cloud-init[1559]:   policycoreutils-2.9-3.el8_1.1.x86_64
[  249.178496] cloud-init[1559]:   policycoreutils-python-utils-2.9-3.el8_1.1.noarch
[  249.186980] cloud-init[1559]:   python3-audit-3.0-0.13.20190507gitf58ec40.el8.x86_64
[  249.195444] cloud-init[1559]:   python3-perf-4.18.0-147.8.1.el8_1.x86_64
[  249.199284] cloud-init[1559]:   python3-policycoreutils-2.9-3.el8_1.1.noarch
[  249.202201] cloud-init[1559]:   python3-rpm-4.14.2-26.el8_1.x86_64
[  249.203812] cloud-init[1559]:   rpm-4.14.2-26.el8_1.x86_64
[  249.210202] cloud-init[1559]:   rpm-build-libs-4.14.2-26.el8_1.x86_64
[  249.211731] cloud-init[1559]:   rpm-libs-4.14.2-26.el8_1.x86_64
[  249.214768] cloud-init[1559]:   rpm-plugin-selinux-4.14.2-26.el8_1.x86_64
[  249.222411] cloud-init[1559]:   rpm-plugin-systemd-inhibit-4.14.2-26.el8_1.x86_64
[  249.246303] cloud-init[1559]:   sqlite-libs-3.26.0-4.el8_1.x86_64
[  249.258599] cloud-init[1559]:   sssd-client-2.2.0-19.el8_1.1.x86_64
[  249.259411] cloud-init[1559]:   sssd-common-2.2.0-19.el8_1.1.x86_64
[  249.265450] cloud-init[1559]:   sssd-kcm-2.2.0-19.el8_1.1.x86_64
[  249.275312] cloud-init[1559]:   sssd-nfs-idmap-2.2.0-19.el8_1.1.x86_64
[  249.279627] cloud-init[1559]:   sudo-1.8.25p1-8.el8_1.1.x86_64
[  249.286893] cloud-init[1559]:   systemd-239-18.el8_1.5.x86_64
[  249.291747] cloud-init[1559]:   systemd-libs-239-18.el8_1.5.x86_64
[  249.300204] cloud-init[1559]:   systemd-pam-239-18.el8_1.5.x86_64
[  249.312797] cloud-init[1559]:   systemd-udev-239-18.el8_1.5.x86_64
[  249.313945] cloud-init[1559]:   tuned-2.12.0-3.el8_1.1.noarch
[  249.319435] cloud-init[1559]: Installed:
[  249.319517] cloud-init[1559]:   kernel-4.18.0-147.8.1.el8_1.x86_64
[  249.319588] cloud-init[1559]:   kernel-core-4.18.0-147.8.1.el8_1.x86_64
[  249.328889] cloud-init[1559]:   kernel-modules-4.18.0-147.8.1.el8_1.x86_64
[  249.331546] cloud-init[1559]:   grub2-tools-efi-1:2.02-78.el8_1.1.x86_64
[  249.341147] cloud-init[1559]:   linux-firmware-20190516-94.git711d3297.el8.noarch
[  249.344599] cloud-init[1559]: Complete!
[  250.120802] cloud-init[1559]: Last metadata expiration check: 0:03:25 ago on Wed 22 Apr 2020 06:59:59 AM UTC.
[  250.515254] cloud-init[1559]: Dependencies resolved.
[  250.531925] cloud-init[1559]: ================================================================================
[  250.532148] cloud-init[1559]:  Package            Arch   Version                              Repo       Size
[  250.532478] cloud-init[1559]: ================================================================================
[  250.532609] cloud-init[1559]: Installing:
[  250.532710] cloud-init[1559]:  python36           x86_64 3.6.8-2.module_el8.1.0+245+c39af44f  AppStream  19 k
[  250.532804] cloud-init[1559]: Installing dependencies:
[  250.532902] cloud-init[1559]:  python3-pip        noarch 9.0.3-15.el8                         AppStream  19 k
[  250.533006] cloud-init[1559]:  python3-setuptools noarch 39.2.0-5.el8                         BaseOS    162 k
[  250.533254] cloud-init[1559]: Enabling module streams:
[  250.533381] cloud-init[1559]:  python36                  3.6
[  250.533509] cloud-init[1559]: Transaction Summary
[  250.533609] cloud-init[1559]: ================================================================================
[  250.533714] cloud-init[1559]: Install  3 Packages
[  250.533846] cloud-init[1559]: Total download size: 201 k
[  250.533975] cloud-init[1559]: Installed size: 466 k
[  250.534189] cloud-init[1559]: Downloading Packages:
[  251.223900] cloud-init[1559]: (1/3): python36-3.6.8-2.module_el8.1.0+245+c39a 352 kB/s |  19 kB     00:00
[  251.236490] cloud-init[1559]: (2/3): python3-pip-9.0.3-15.el8.noarch.rpm      332 kB/s |  19 kB     00:00
[  251.284498] cloud-init[1559]: (3/3): python3-setuptools-39.2.0-5.el8.noarch.r 1.4 MB/s | 162 kB     00:00
[  251.299425] cloud-init[1559]: --------------------------------------------------------------------------------
[  251.301591] cloud-init[1559]: Total                                           262 kB/s | 201 kB     00:00
[  251.304472] cloud-init[1559]: Running transaction check
[  251.325543] cloud-init[1559]: Transaction check succeeded.
[  251.340785] cloud-init[1559]: Running transaction test
[  251.373363] cloud-init[1559]: Transaction test succeeded.
[  251.389583] cloud-init[1559]: Running transaction
[  251.508700] cloud-init[1559]:   Preparing        :                                                        1/1
[  251.541868] cloud-init[1559]:   Installing       : python3-setuptools-39.2.0-5.el8.noarch                 1/3
[  251.573250] cloud-init[1559]:   Installing       : python36-3.6.8-2.module_el8.1.0+245+c39af44f.x86_64    2/3
[  251.618669] cloud-init[1559]:   Running scriptlet: python36-3.6.8-2.module_el8.1.0+245+c39af44f.x86_64    2/3
[  251.673787] cloud-init[1559]:   Installing       : python3-pip-9.0.3-15.el8.noarch                        3/3
[  OK  ] Started /usr/bin/systemctl start man-db-cache-update.
[  251.884829] cloud-init[1559]:   Running scriptlet: python3-pip-9.0.3-15.el8.noarch                        3/3
[  251.897856] cloud-init[1559]:   Verifying        : python3-pip-9.0.3-15.el8.noarch                        1/3
[  251.901159] cloud-init[1559]:   Verifying        : python36-3.6.8-2.module_el8.1.0+245+c39af44f.x86_64    2/3
[  252.070607] cloud-init[1559]:   Verifying        : python3-setuptools-39.2.0-5.el8.noarch                 3/3
[  252.087665] cloud-init[1559]: Installed:
[  252.087775] cloud-init[1559]:   python36-3.6.8-2.module_el8.1.0+245+c39af44f.x86_64
[  252.087879] cloud-init[1559]:   python3-pip-9.0.3-15.el8.noarch
[  252.087985] cloud-init[1559]:   python3-setuptools-39.2.0-5.el8.noarch
[  252.088360] cloud-init[1559]: Complete!
[  252.587247] cloud-init[1559]: Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
[  253.900503] cloud-init[1559]: CentOS-8 - AppStream                             13 kB/s | 4.3 kB     00:00
[  254.456741] cloud-init[1559]: CentOS-8 - Base                                 7.4 kB/s | 3.8 kB     00:00



Anyway, I think it is low-priority for now.

**Comment by maelk** [comment]
Solved by #330
