### ISSUE TITLE
user without a github token now can not fetch providers during "clusterctl init" 

### ISSUE THREAD

**Issue by bigben80** [metal3-io/metal3-dev-env#307]
Hi, 

I'm using metal3 provisioning VMs during last several weeks, from this week I got following error messages in step "03_launch_mgmt_cluster.sh":

_+ ./clusterctl init --infrastructure=metal3:null -v5
Using configuration File="/home/ubuntu/.cluster-api/clusterctl.yaml"
Installing the clusterctl inventory CRD
Creating CustomResourceDefinition="providers.clusterctl.cluster.x-k8s.io"
Fetching providers
Error: failed to get provider components for the "cluster-api" provider: failed to get repository client for the CoreProvider with name cluster-api: error creating the GitHub repository client: failed to get GitHub latest version: failed to get the list of versions: rate limit for github api has been reached. Please wait one hour or get a personal API tokens a assign it to the GITHUB_TOKEN environment variable_

Tried to use latest commit, and roll back to older commit, either doesn't work. do we have some limitation for this repo now?

Testing environment is on Ubuntu 18.04, commits between April 30th and May 7th are tested.

**Comment by maelk** [comment]
We are now using clusterctl as part of the metal3-dev-env deployment flow. Depending on your setup, you might end up hitting the rate limit from Github. It is however very easy to work around, by getting a token from github (no permissions needed) and setting it in the GITHUB_TOKEN environment variable.

**Comment by bigben80** [comment]
Hi maelk,

Thanks for the update, I'll use a token instead.

> We are now using clusterctl as part of the metal3-dev-env deployment flow. Depending on your setup, you might end up hitting the rate limit from Github. It is however very easy to work around, by getting a token from github (no permissions needed) and setting it in the GITHUB_TOKEN environment variable.
