### ISSUE TITLE
Support for running it on GCP

### ISSUE THREAD

**Issue by sb1975** [metal3-io/metal3-dev-env#31]
I followed the steps to create a GCP VM instance using 8vCPU,Intel Haswell,32GB RAM with nested Virtualization enabled.
https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances
http://www.brianlinkletter.com/enable-nested-virtualization-on-google-cloud/

However the Ansible playbook failed with below error :
"stderr": "(1): Command failed: Fail to establish a connection with libvirt URI \"qemu+ssh://root@192.168.111.1/system?&keyfile=/root/.ssh/id_rsa_virt_power&no_verify=1&no_tty=1\". Error: Cannot recv data: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).: Connection reset by peer",

I think the passwordless root access is mandatory ? Isnt there a way to execute it if passwordless root access is not there  and just using the sudo ?

**Comment by russellb** [comment]
This error doesn't seem related to the use of GCP and nested virt.

Passwordless root is not required.  The scripts do run `sudo` several times, so it's convenient to set up passwordless sudo, though also shouldn't be required.

The scripts create the `/root/.ssh/id_rsa_virt_power` ssh key.  Is it present?

**Comment by dhellmann** [comment]
Is this still an issue?

**Comment by russellb** [comment]
feel free to reopen if needed
