### ISSUE TITLE
Parameterize controllers' versions

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/metal3-dev-env#351]
At the moment, the [CAPM3RELEASEPATH](https://github.com/metal3-io/metal3-dev-env/blob/ad969a89d4d47f025c3a03d3d4bfa621a6026aa1/lib/common.sh#L104
) parameterize  CAPM3 versions. 

If other controllers are also parameterized in the same manner, it would allow make controlplane-components upgrade process predictable.

**Comment by maelk** [comment]
If I understood correctly, you're rather wanting to parameterize the versions of the controllers deployed, i.e. parameterize the clusterctl init command like `--infrastructure=metal3:"${CAPM3RELEASE}"` to be able to deploy a specific version of each, if they are already published. Is that right ?

**Comment by Xenwar** [comment]
> If I understood correctly, you're rather wanting to parameterize the versions of the controllers deployed, i.e. parameterize the clusterctl init command like `--infrastructure=metal3:"${CAPM3RELEASE}"` to be able to deploy a specific version of each, if they are already published. Is that right ?

Yes, that is correct.

**Comment by Xenwar** [comment]
Simple grepping, I see that only CAPM3 is deployed via `cluster init`.
Could there be other locations, other than metal3-dev-env where other controllers are deployed the same way ?

**Comment by maelk** [comment]
the rest of the controllers are deployed by default, you can omit the parameters in clusterctl init. so they would need to be added and parameterized

**Comment by Xenwar** [comment]
Handled by https://github.com/metal3-io/metal3-dev-env/pull/361.
CAPM3 release was already configurable

**Comment by maelk** [comment]
closing this then. Please re-open if needed
/close
