### ISSUE TITLE
Pod network connectivity broken with calico and kube proxy

### ISSUE THREAD

**Issue by udayruddarraju** [metal3-io/metal3-dev-env#369]
## Environment Setup

I could not find a good doc in the metal3 documentation that describes or mentions the calico manifest and changes that need to be applied to the target cluster to get the Nodes into a Ready state. Once the environment is setup using provision_cluster, provision_controlplane and provision_workers, this is the state of my management cluster and target cluster.

```
AzureUser@metal3-demo:~/metal3/metal3-dev-env$ kubectl get machines -A
NAMESPACE   NAME                   PROVIDERID                                      PHASE
metal3      test1-ff7bdbf7-pfvjf   metal3://9acc9757-0fe5-421b-b99a-b191dd6b459c   Running
metal3      test1-h5sfb            metal3://67734269-742e-4706-a927-c51deafbf66b   Running
metal3      test1-jsr7h            metal3://d457c517-8475-4dbe-81bf-fab215b1a7a9   Running
metal3      test1-lc645            metal3://d7ecd25b-4a8c-4777-ab40-ba4e490d520e   Running
```

```
AzureUser@metal3-demo:~/metal3/metal3-dev-env$ kubectl get baremetalhosts -A
NAMESPACE   NAME     STATUS   PROVISIONING STATUS   CONSUMER                   BMC                         HARDWARE PROFILE   ONLINE   ERROR
metal3      node-0   OK       ready                                            ipmi://192.168.111.1:6230   unknown            false
metal3      node-1   OK       provisioned           test1-controlplane-6qdjt   ipmi://192.168.111.1:6231   unknown            true
metal3      node-2   OK       provisioned           test1-workers-znq5c        ipmi://192.168.111.1:6232   unknown            true
metal3      node-3   OK       provisioned           test1-controlplane-nb4vf   ipmi://192.168.111.1:6233   unknown            true
metal3      node-4   OK       provisioned           test1-controlplane-9grrh   ipmi://192.168.111.1:6234   unknown            true
```

```
AzureUser@metal3-demo:~/metal3/metal3-dev-env$ kubectl get nodes --kubeconfig ./workload-cluster.kubeconfig -o wide
NAME     STATUS      ROLES    AGE     VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
node-1   NotReady    master   11h     v1.18.0   192.168.111.21   <none>        CentOS Linux 8 (Core)   4.18.0-147.3.1.el8_1.x86_64   docker://18.9.1
node-2   NotReady    <none>   3h40m   v1.18.0   192.168.111.22   <none>        CentOS Linux 8 (Core)   4.18.0-147.3.1.el8_1.x86_64   docker://18.9.1
node-3   NotReady    master   11h     v1.18.0   192.168.111.23   <none>        CentOS Linux 8 (Core)   4.18.0-147.3.1.el8_1.x86_64   docker://18.9.1
node-4   NotReady    master   11h     v1.18.0   192.168.111.24   <none>        CentOS Linux 8 (Core)   4.18.0-147.3.1.el8_1.x86_64   docker://18.9.1
```

The POD_CIDR being used is the default POD_CIDR: `192.168.0.0/18`

As you can see above, the nodes are not ready because the CNI is not deployed yet. I went ahead and deployed calico by:

- Downloading calico manifest from https://docs.projectcalico.org/v3.15/manifests/calico.yaml
- Changing CALICO_IPV4POOL_CIDR
```
    - name: CALICO_IPV4POOL_CIDR
      value: 192.168.0.0/18
```
- And applied it.

The above has brought the nodes to be healthy.

## The Problem

Created three different pods by running:
```
kubectl run nginx --image=nginx  --kubeconfig ./workload-cluster.kubeconfig
kubectl run nginx1 --image=nginx  --kubeconfig ./workload-cluster.kubeconfig
kubectl run nginx2 --image=nginx  --kubeconfig ./workload-cluster.kubeconfig
```

And I see that nginx, nginx1 and nginx2 are all not able to communicate with the kube apiserver, and also not able to reach outside(curl to www.google.com times out) and not able to reach each other. Coredns pods scheduled on non-master nodes are also not coming up healthy because they are not able to reach the apiserver through kube proxy

If I delete all iptable rules on the box, pod to pod traffic works, but pod to internet and pod to kube-proxy managed services is still failing.

I am sure I am missing something here and reached out to a couple others who also faced similar problems and wanted to see if we are missing something here. Appreciate your help in advance. I would be happy to submit a documentation PR once I resolve this to help explain setting up a ready kubernetes cluster post provisioning of machines.

**Comment by maelk** [comment]
We have an example setup of calico on the deployed nodes in metal3-dev-env deployment verifications scripts : https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/roles/v1aX_integration_test/tasks/verify.yml#L83 . To get it working, we had to change the CIDR as you did, but then also change the autodetection method. Have a look and let us know if that helps.

**Comment by maelk** [comment]
That would anyways benefit from a documentation update.

**Comment by uruddarraju** [comment]
I actually did both changing the cidr and also setting the autodetection to be interface=eth1 without luck. Any pods that is deployed on the cluster worker nodes is having connectivity issues. Also it is not clear how should the ironic deployment move while we pivot? Is it expected for ironic to work when the management control plane is moved into the target cluster eventually?

**Comment by maelk** [comment]
the pivoting is another story, and will not be successful as long as you do not have a proper setup on the target cluster, including the CNI. Could you give more info, such as the calico deployment you applied, the logs of the failing pods, the logs of the calico pods etc.

**Comment by udayruddarraju** [comment]
I think I was able to fix this by running the following iptables clear before I installed calico on all nodes:

```
iptables -P FORWARD ACCEPT
iptables -P INPUT ACCEPT
```

This fixed a few issues for me. I think there might be some default iptable rules that are being created during cloudinit/initial bootstrap that might be causing a few issues for me.

**Comment by udayruddarraju** [comment]
I will close this for now as I found a work around.
