### ISSUE TITLE
Validate the deployment

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-dev-env#39]
Adding a validation script would help catch issues in the deployment. Specially in CI, the metal3-dev-env deployment needs to be checked. The following points should probably be verified :
- Running kubernetes cluster, reachable
- Running baremetal operator
- Running CAPI provider baremetal operator
- CRDs defined
- Host vms defined
- Networking ok
- Ironic containers running
- baremetal hosts CRs created

We could create a make target to check the setup after deployment

**Comment by russellb** [comment]
+1 to the idea of some automated validation of this env running in CI

**Comment by maelk** [comment]
The basic test is in place and should be expanded when features are added.
We should probably consider moving from a bash script to another testing framework, especially considering that we will need to validate the deployment of Kubernetes on the machines at some point, using SSH. We should probably switch to a full-fledge framework like Robot or something lighter, for example just using Ansible.

**Comment by stbenjam** [comment]
Per @maelk, this isn't relevant any more.

/close
