### ISSUE TITLE
Correct steps to deploy metal3-dev-env using docker and v1alpha4

### ISSUE THREAD

**Issue by sb1975** [metal3-io/metal3-dev-env#409]
When I specify CONTAINER_RUNTIME=docker and CAPM3_VERSION=v1alpha4 , 
the script https://github.com/metal3-io/metal3-dev-env/blob/master/scripts/feature_tests/feature_test_provisioning.sh 
keeps running indefinitely... is something broken pls ?

<localhost> EXEC /bin/sh -c 'echo ~esudbat && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/esudbat/.ansible/tmp/ansible-tmp-1596491744.3007896-263230451493007 `" && echo ansible-tmp-1596491744.3007896-263230451493007="` echo /home/esudbat/.ansible/tmp/ansible-tmp-1596491744.3007896-263230451493007 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/commands/command.py
<localhost> PUT /home/esudbat/.ansible/tmp/ansible-local-257737a_8oiyg/tmprxjxfcw8 TO /home/esudbat/.ansible/tmp/ansible-tmp-1596491744.3007896-263230451493007/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/esudbat/.ansible/tmp/ansible-tmp-1596491744.3007896-263230451493007/ /home/esudbat/.ansible/tmp/ansible-tmp-1596491744.3007896-263230451493007/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/esudbat/.ansible/tmp/ansible-tmp-1596491744.3007896-263230451493007/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/esudbat/.ansible/tmp/ansible-tmp-1596491744.3007896-263230451493007/ > /dev/null 2>&1 && sleep 0'

...

Appreciate any help to fix it..

**Comment by dhellmann** [comment]
This readme may help: https://github.com/metal3-io/metal3-dev-env/blob/master/scripts/feature_tests/README.md

**Comment by dhellmann** [comment]
These docs may also help: https://metal3.io/blog/2020/02/18/metal3-dev-env-install-deep-dive.html and https://metal3.io/blog/2020/06/18/Metal3-dev-env-BareMetal-Cluster-Deployment.html

**Comment by fmuyassarov** [comment]
@sb1975 Can you please specify what were you trying to run or achieve? Because, `feature_test_provisioning.sh` is used to test pivoting and remediation related tests.
