### ISSUE TITLE
Move Ironic into the cluster

### ISSUE THREAD

**Issue by russellb** [metal3-io/metal3-dev-env#41]
The scripts currently run the ironic containers on the host.  All of these containers should move into the cluster as part of the baremetal-operator pod.  The baremetal-operator repo includes a sample pod manifest that includes ironic as a starting point.  It will likely need some additions to ensure the pod downloads some required images - IPA and an OS image like the CentOS image that the scripts download right now.

**Comment by ogelbukh** [comment]
Note that current version of the [Metal3 chart](https://github.com/metal3-io/metal3-helm-chart) deploys Ironic as a pod. The next step would be to modify source images to use dedicated images per service container.
