### ISSUE TITLE
Pivot fails

### ISSUE THREAD

**Issue by sb1975** [metal3-io/metal3-dev-env#410]
Pivot to the target cluster
./scripts/provision/pivot.sh

When I run the above script, it fails with below error : 
The full traceback is:
  File "/tmp/ansible_docker_container_payload_yx1i62ad/ansible_docker_container_payload.zip/ansible/module_utils/docker/common.py", line 361, in __init__
    super(AnsibleDockerClient, self).__init__(**self._connect_params)
  File "/usr/local/lib/python3.6/dist-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.6/dist-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)

failed: [localhost] (item=ironic-endpoint-keepalived) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version":
...
    },
    "item": "ironic-endpoint-keepalived",
    "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"
}

**Comment by fmuyassarov** [comment]
Seems that `ironic-endpoint-keepalived` isn't present in the source cluster. It is failing while trying to delete the container [here
](https://github.com/metal3-io/metal3-dev-env/blob/0fb1740f4402bef689c24e83ecfee42b31246b9f/vm-setup/roles/v1aX_integration_test/tasks/move.yml#L2).
Can you please check if you have `ironic-endpoint-keepalived` container running in the source cluster?
/cc @kashifest

**Comment by fmuyassarov** [comment]
@sb1975 are you able to reproduce the issue?

**Comment by furkatgofurov7** [comment]
priority/awaiting-more-evidence
