### ISSUE TITLE
No automatic switching between branches

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/metal3-dev-env#434]
I run Metal3-dev-env with `CAPI_VERSION=v1alpha3` for the first time. After successful deployment, I run `make clean` and run `make` again but this time with  `CAPI_VERSION=v1alpha4` & `CAPM3_VERSION=-v1alpha4`. 
However, Metal3-dev-env scripts don't take care of switching between branches based on CAPM3_VERSION variable and that's why I see the following error when I run with different CAPM3_VERSION than the first time:
```
+ '[' v1alpha4 '!=' v1alpha3 ']'
+ make set-manifest-image-bmo
make[1]: Entering directory '/home/ubuntu/go/src/github.com/metal3-io/cluster-api-provider-metal3'
make[1]: *** No rule to make target 'set-manifest-image-bmo'.  Stop.
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/metal3-io/cluster-api-provider-metal3'
make: *** [Makefile:10: launch_mgmt_cluster] Error 2
```

What I expect from the second run is cluster-api-provider-metal3 that is cloned into /go/src/github.com/metal3-io/cluster-api-provider-metal3 switches to the correct branch based on the `CAPM3_VERSION` environment variable value.
Because CAPM3_VERSION is the variable to manipulate the branch name I want to use for CAPM3. 

**How to reproduce:**
In this run scripts will clone cluster-api-provider-metal3 repo and switch to the `release-0.3` branch.
```
export CAPI_VERSION=v1alpha3
make
make clean
```

But when running here, some scripts require master branch of CAPM3, but automatic switching to the master branch is not done.
```
export CAPI_VERSION=v1alpha4
make
```

**Comment by maelk** [comment]
We had implemented this behaviour, but had to revert it because it was overriding local changes. You could go around the issue by setting the FORCE_REPO_UPDATE to true

**Comment by maelk** [comment]
yes, I think a documentation update would be the best way to go

**Comment by furkatgofurov7** [comment]
> yes, I think a documentation update would be the best way to go

Just to make sure, I will update metal3-io.github.io/try-it.md if this is the right place to do so or is metal3-dev-env/README.me needs to be edited as well?

**Comment by maelk** [comment]
probably wherever `make clean` is mentioned, we should add a note that redeploying with a different branch requires this variable set
