### ISSUE TITLE
Machine Provisioning Failing in case of non-default baremetal & provisioning networks, need to parameterize the external_subnet_v4

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/metal3-dev-env#462]
We tried to setup metal3-dev-env using non-default baremetal & provisioning networks, Target-OS=Ubuntu.
Node provisioning & SSH login using metal3 user was successful. However Machine provisioning had failed as seen CAPI & CAPM3 logs.

EXTERNAL_SUBNET_V4=192.168.115.0/24
PROVISIONING_NETWORK=192.168.100.0/24

`I0918 13:35:33.354511       1 machine_controller_noderef.go:52] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="test1" "machine"="test1-gv7gw" "namespace"="metal3" 
E0918 13:35:33.354577       1 machine_controller.go:266] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Infrastructure provider for Machine \"test1-gv7gw\" in namespace \"metal3\" is not ready, requeuing: requeue in 30s" "cluster"="test1" "machine"="test1-gv7gw" "namespace"="metal3" `

` 13:17:57.999490       1 metal3machine_manager.go:706] controllers/Metal3Machine/Metal3Machine-controller "msg"="Finished updating machine" "cluster"="test1" "machine"="test1-gv7gw" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-controlplane-k4z27"} 
I0918 13:17:59.002389       1 metal3machine_manager.go:1127] controllers/Metal3Machine/Metal3Machine-controller "msg"="error while accessing cluster: Get https://192.168.115.249:6443/api/v1/nodes?labelSelector=metal3.io%2Fuuid%3D22a0c282-c69a-47be-ae99-0e6622b2c4e6: dial tcp 192.168.115.249:6443: connect: connection refused" "cluster"="test1" "machine"="test1-gv7gw" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-controlplane-k4z27"} `

On further debugging found that parameter **external_subnet_v4** in **_metal3-dev-env/vm-setup/roles/firewall/defaults/main.yml_** is hard-coded. Changing this value to above mentioned desired value, fixed the issue. Hence need to remove this hard-coding and parameterize the same. Please scan for all such other parameters which are hard-coded to make metal3-dev-env fully customizable.

@fmuyassarov : Kindly share your inputs.

**Comment by fmuyassarov** [comment]
Sorry for that @sumitjadhav1 . I agree that exporting `EXTERNAL_SUBNET_V4` with custom value or even putting a hardcoded value in lib/images.sh will not be propagated in [vm-setup/roles/firewall/defaults/main.yml](https://github.com/metal3-io/metal3-dev-env/blob/e84aa8225a681990d3712d1291e151e1ec566a0f/vm-setup/roles/firewall/defaults/main.yml#L4). We were missing a lookup in there. Here is the fix https://github.com/metal3-io/metal3-dev-env/pull/463.
