### ISSUE TITLE
Add Redfish emulator in dev env

### ISSUE THREAD

**Issue by jan-est** [metal3-io/metal3-dev-env#47]
We want add Redfish support to metal3 to use Redfish interface instead of IPMI. We are thinking to add Redfish emulator like sushy-tool in dev env in parralel of VBMC: https://github.com/openstack/sushy-tools

**Comment by jan-est** [comment]
@maelk @alanmeadows for airship integration

**Comment by russellb** [comment]
sounds good to me, thanks for opening the issue to track it.

**Comment by hardys** [comment]
https://github.com/metal3-io/metal3-dev-env/pull/48 merged, so can we close this now?
