### ISSUE TITLE
Failing to onboard/introspect real nodes in Metal3

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/metal3-dev-env#491]
We're using latest code of metal3-dev-env & our custom changes to introspect real nodes i.e. Dell PowerEdge servers.
But it's failing at NBP file download step. Need help from community.

BaseOS=Ubuntu, Kind-Cluster, Container-runtime=docker

Attaching log files & changes we make during successful installation metal3-dev-env.
Discussed with @fmuyassarov , @kashifest , the changes done look correct till Node to be in Ready state.
[metal3-issue.zip](https://github.com/metal3-io/metal3-dev-env/files/5305147/metal3-issue.zip)

Points to note :
1. Initially when virtual nodes (node-0,1) are created by default in dev-env, these are introspected successfully.
Facing issues further with real nodes only.
2. This issue is seen recently (from last week only), until then everything used to work fine with changes we do for real nodes.

**Comment by sumitjadhav1** [comment]
cc @digambar15 @snehal1797

**Comment by dtantsur** [comment]
Could you open the iDRAC virtual console and check what is actually happening on the nodes? Maybe make a screenshot.

Please make sure you have the latest firmware. Also check if any changes have been made to your network configuration (especially things like MTU).

**Comment by fmuyassarov** [comment]
/remove-lifecycle stale
@sumitjadhav1 Any updates on this issue? Is it still an issue for you?

**Comment by sumitjadhav1** [comment]
Hi Feruz, sorry for delayed response.
When checked with old commit (somewhere around first week of February 2021), issue was still there. 
Will update the observations with the latest commits this or next week, possibly before meeting.

**Comment by sumitjadhav1** [comment]
This issue is no longer observed. Can close for now. Will re-open if seen again.

[Verification-RAM-Parameter.txt](https://github.com/metal3-io/metal3-dev-env/files/6531837/Verification-RAM-Parameter.txt)

Logs to confirm that we were able to on-board real nodes (PowerEdge servers) in Metal3.
