### ISSUE TITLE
./05_test.sh Failed in deply controlpalne. 

### ISSUE THREAD

**Issue by chenkaigithub** [metal3-io/metal3-dev-env#531]
I follow make clean and make to do some test.
It's failed in 05_test.sh.

Result :

NAMESPACE NAME STATUS PROVISIONING STATUS CONSUMER BMC HARDWARE PROFILE ONLINE ERROR
metal3 node-0 OK ready ipmi://192.168.111.1:6230 unknown true
metal3 node-1 OK provisioned test1-controlplane-xjbkn redfish+http://192.168.111.1:8000/redfish/v1/Systems/d8cf11c3-bfc6-4818-8ee9-420680b34ba5 unknown true

In /var/log/message in test1-controlplane-xjbkn , the following error is shown. /var/lib/kubelet/config.yaml is not existed. I think cloud-init is failed. How can I sovle this?

Oct 27 16:00:16 test1-w28ns systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Oct 27 16:00:16 test1-w28ns systemd[1]: kubelet.service: Failed with result 'exit-code'.
Oct 27 16:00:26 test1-w28ns systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
Oct 27 16:00:26 test1-w28ns systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 5.
Oct 27 16:00:26 test1-w28ns systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Oct 27 16:00:26 test1-w28ns systemd[1]: Started kubelet: The Kubernetes Node Agent.
Oct 27 16:00:26 test1-w28ns kubelet[1733]: F1027 16:00:26.413079 1733 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory

**Comment by fmuyassarov** [comment]
Can you please share what env variables you have exported before you run make/
What OS are you using to run metal3-dev-env?

**Comment by chenkaigithub** [comment]
OS : Cent OS 8(core-4.1-amd64:core-4.1-noarch)
I use the default settings.

**Comment by chenkaigithub** [comment]
I check the control-plane VM's log.
It seems cloud-init is failed, so kubeadm is not initialized.

**Comment by hroyrh** [comment]
I was able to reproduce this issue with a latest metal3-dev-env deployment, error line from kubelet service inside controlplane : 
```
server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
```
OS : Rhel8.3 ( 4.18.0-193.el8.x86_64 )
Config : IP_STACK=v4, rest setting default

**Comment by fmuyassarov** [comment]
Not sure what is causing that. From the master [integration CI](https://jenkins.nordix.org/view/Airship/job/airship_master_v1a4_integration_test_centos/426/console) I can see that job passed last night when running on top of Centos. I will run a test myself on CentOS 8 and update here.

**Comment by fmuyassarov** [comment]
Hi, sorry for the late reply. It seems kubelet config file isn't present on the target node.
Can you please if you have a configMap  `kubelet-config-1.19` in `kube-system` namespace ?
```
$ kubectl get cm -A
NAMESPACE     NAME                                 DATA   AGE
kube-public   cluster-info                         3      58s
kube-system   coredns                              1      58s
kube-system   extension-apiserver-authentication   6      65s
kube-system   kube-proxy                           2      58s
kube-system   kubeadm-config                       2      59s
kube-system   kubelet-config-1.19                  1      59s

```
Also, probably you don't have `/var/lib/kubelet/config.yaml` file within the node right?

**Comment by hroyrh** [comment]
I do have `kubelet-config-1.20` in the `kube-system` namespace, but yes I don't have the `/var/lib/kubelet` directory inside the controlplane node.

**Comment by hroyrh** [comment]
This is weird because, I didn't export the `KUBERNETES_VERSION` var, are you using the latest metal3-dev-env code ?

**Comment by fmuyassarov** [comment]
> This is weird because

Yes, and you can see that it [here](https://github.com/metal3-io/metal3-dev-env/blob/83b42a59c23f134fb9e0f4ceb05d2c77a9f12c6c/lib/common.sh#L185) that it is set to 1.19.3

**Comment by hroyrh** [comment]
Okay let me retry a fresh deployment and see what happens.

**Comment by fmuyassarov** [comment]
Hi @hroyrh ,
Any updates from your tests?

**Comment by hroyrh** [comment]
Hi @fmuyassarov , I tried on Rhel8 but had some issues with deployment. I will check if this issue is also part of it after a bit more testing, will let you know once I have done that.

**Comment by fmuyassarov** [comment]
Thanks. After quick googling, found this [issue ](https://github.com/kubernetes/kubernetes/issues/73779) which has similar sort of logs. Not sure thought if there was something similar happening in your environment.
