### ISSUE TITLE
Failed deploy Metal Kubed (Ubuntu 20.04)

### ISSUE THREAD

**Issue by Mawwlle** [metal3-io/metal3-dev-env#560]
**Environment:** Ubuntu 20.04(same problem on Ubuntu 18.04), 32 gb ram, 8 CPUs (oVirt, kvm)
**What have we tried to do:** deploy on CentOS 7, editing configuration files, various environment settings

**This error occurs while running ./02_configure_host.sh**

![Снимок экрана 2020-11-22 в 12 58 36](https://user-images.githubusercontent.com/44709362/99903456-a0a8b800-2cd5-11eb-8d8c-53f13e25ea76.png)

**Comment by maelk** [comment]
This looks like qemu does not support kvm. Is virtualization enabled ?

**Comment by Mawwlle** [comment]
> This looks like qemu does not support kvm. Is virtualization enabled ?

Virtualization disabled. I understand that the problem is most likely in this. 
**Is there a workaround other than enabling virtualization?**

**Comment by maelk** [comment]
not in metal3-dev-env unfortunately. We rely only on kvm.
