### ISSUE TITLE
Failing to provision with the latest  sushy-tools (0.15.0)

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/metal3-dev-env#610]
After upgrading sushy-tools to 0.15.0, BMH could not get provisioned.

```
NAMESPACE   NAME     STATUS   STATE            CONSUMER                   BMC
                                                    HARDWARE_PROFILE   ONLINE   ERROR
metal3      node-0   OK       ready                                       ipmi://192.168.111.1:6230
                                                    unknown            true
metal3      node-1   OK       deprovisioning   test1-controlplane-22rcl   redfish+http://192.168.111.1:8000/redfis
h/v1/Systems/2cd7ddb7-956c-4664-b8cc-b19b37952fb6   unknown            false
```

```
baremetal node list
+--------------------------------------+--------+---------------+-------------+--------------------+-------------+
| UUID                                 | Name   | Instance UUID | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------+---------------+-------------+--------------------+-------------+
| 217f36ed-3d37-4e23-8bea-8f2da8e5ab22 | node-0 | None          | power on    | manageable         | False       |
| 29e8e3a9-bc1f-4472-a668-e83a06e28c43 | node-1 | None          | power on    | clean wait         | False       |
+--------------------------------------+--------+---------------+-------------+--------------------+-------------+
```

We need to investigate the issue with sushy-tools 0.15.0. Apart from that, while running integration CI on a patch we need to make sure that we always build local images of sushy-tools and vbmc instead of pulling them from Quay. Because, pulling images from Quay won't help us to recognize possible issues during CI check on the patch.

This discussion started in https://github.com/metal3-io/metal3-dev-env/pull/609

**Comment by hardys** [comment]
It sounds like https://github.com/metal3-io/metal3-dev-env/pull/606/files#r595873052 may explain this problem, so I can propose a revised PR which fixes that.

It'd be good to get CI coverage of these changes though, to avoid this kind of breakage in the future - I think if we can set SUSHY_TOOLS_LOCAL_IMAGE in metal3-dev-env CI so it points to the git checkout, that should work?

https://github.com/metal3-io/metal3-dev-env/blob/master/02_configure_host.sh#L190

**Comment by fmuyassarov** [comment]
> It sounds like https://github.com/metal3-io/metal3-dev-env/pull/606/files#r595873052 may explain this problem, so I can propose a revised PR which fixes that.
> 
> It'd be good to get CI coverage of these changes though, to avoid this kind of breakage in the future - I think if we can set SUSHY_TOOLS_LOCAL_IMAGE in metal3-dev-env CI so it points to the git checkout, that should work?

Right, but I think `SUSHY_TOOLS_LOCAL_IMAGE` in metal3-dev-env is already in [place](https://github.com/metal3-io/metal3-dev-env/blob/c0eaf956828e0aee80a596812ac919128c67edd1/02_configure_host.sh#L190), so we need it to be exported in [project-infra](https://github.com/metal3-io/project-infra/blob/81577033b32d3e4cd25401077704fb91ab3247b6/jenkins/scripts/files/run_integration_tests.sh#L122), like we do for [`IRONIC_LOCAL_IMAGE`](https://github.com/metal3-io/project-infra/blob/81577033b32d3e4cd25401077704fb91ab3247b6/jenkins/scripts/files/run_integration_tests.sh#L88).

**Comment by fmuyassarov** [comment]
and if we are going to do that, we would need to export `VBMC_LOCAL_IMAGE` as well.

**Comment by hardys** [comment]
@fmuyassarov I proposed https://github.com/metal3-io/project-infra/pull/175 PTAL, thanks!

**Comment by fmuyassarov** [comment]
Closing this issue as it was fixed in https://github.com/metal3-io/metal3-dev-env/pull/619.
/close
