### ISSUE TITLE
Move node-image building scripts from airship-dev-tools to metal3-dev-env

### ISSUE THREAD

**Issue by kashifest** [metal3-io/metal3-dev-env#613]
Currently, the node-image building scripts reside in aiship-dev-tools instead of metal3-dev-env. As such, users do not have access or view to the pre-kubeadm or post-kubeadm commands. We should probably move them to metal3-dev-env.

**Comment by Xenwar** [comment]
I agree.

**Comment by fmuyassarov** [comment]
If we are going to move node-image building scripts then maybe it would be better to keep them in project-infra? as we store all the CI related stuff in there.

**Comment by kashifest** [comment]
> If we are going to move node-image building scripts then maybe it would be better to keep them in project-infra? as we store all the CI related stuff in there.

TBH, it shouldn't be in project-infra IMO. This is not infra related.
