### ISSUE TITLE
Metal3-dev-env unable to scale capm3-controller-manager

### ISSUE THREAD

**Issue by jan-est** [metal3-io/metal3-dev-env#686]
When I set `CAPM3_LOCAL_RUN=true` metal3-dev-env is unable to create the environment. It is failing because `capm3-controller-manager` deployment can not be found

**Comment by jan-est** [comment]
Metal3-dev-env fails to scale down the capm3-controller-manager because the namespace in 01_ script is wrong. Here is the PR for the fix [687](https://github.com/metal3-io/metal3-dev-env/pull/687)

**Comment by lentzi90** [comment]
The PR was not properly linked. This issue can be closed as of #687

**Comment by furkatgofurov7** [comment]
/close
`
Fixes#` should have been used in fixing PR. Closing manually.
