### ISSUE TITLE
Update to python 3

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-dev-env#88]
In many places we still use python2, we should upgrade before the python2 EOS

**Comment by fmuyassarov** [comment]
I have a [PR#214](https://github.com/metal3-io/metal3-dev-env/pull/214) to use python3 when building Ubuntu based Metal3-dev-env.

**Comment by fmuyassarov** [comment]
@maelk shall we close this issue? If I'm not missing anything, I think we now use python3 in all the places.

**Comment by maelk** [comment]
yes, I think so.
/close
