### ISSUE TITLE
Update control-plane/master taints for k8s v1.24

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/metal3-dev-env#898]
In k8s v1.24 the ["node-role.kubernetes.io/control-plane" taint will be added](https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/XJhn8bpvHac) to control-plane Nodes as part of renaming "node-role.kubernetes.io/master" -> "node-role.kubernetes.io/control-plane".
We rely on the old taint in [at least some tests](https://github.com/metal3-io/metal3-dev-env/blob/620b4e6abef8c0edaedd8dc3cdab2a5b3d0da7bd/vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml#L9). So before we can move to v1.24 we will need to address this.

**Comment by furkatgofurov7** [comment]
@lentzi90 great, thanks for opening this! We have one more case in CAPM3 e2e tests that need a change, see: https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/test/e2e/node_reuse_test.go#L40

**Comment by lentzi90** [comment]
We have already uplifted to v1.24 so this can be closed.
/close
