### ISSUE TITLE
Accomodate upgrade tests better

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/metal3-dev-env#913]
This is a quite broad issue so a bit of background might be helpful:
The metal3-dev-env supports integration and feature tests for the Metal³ stack. It helps with building container images and generating manifests so that the very latest code can be tested. This works well for the feature tests, but when it comes to upgrade tests, things get a bit complicated. This is especially true for the e2e tests in CAPM3.

For all non-upgrade tests, we are basically concerned with building the code that we want to test and using it in the test. This means checking out the correct branch of the correct repo, building the container image, tagging it properly and making sure it is used in the manifests used to install the Metal³ stack.

### Moving between versions

For upgrade tests, we want to start with an old version of everything and then move to the latest. This gets complicated because metal3-dev-env is focused on only one version. We can easily configure metal3-dev-env to set up an environment with an old version but then it will only build and configure this old version. If we then want to upgrade and test the very latest code, we will have to build and push that code as part of the upgrade test itself. (The current upgrade tests rely on pre-built images from the main branch instead of building the "tested" branch in a PR.)

### What images are used?

To make things worse it is also hard to know what code is actually in the image that is running as part of a test. Many images are pushed to the local registry, but not all of them are built locally. They don't have tags to indicate what commit they are from. Some have tags for the branch, but others are just running "latest". The idea is that images from the currently tested repo should be built locally, but it is quite impossible to check if this is the case by just looking at what images are used. I think the image will sometimes be named `tested_repo`, so this would indicate that it is built locally, but then it is not very clear what the image actually is (CAPM3, BMO or something else).

### Running the latest test code with older releases

The same problems appear also in the e2e tests, since they also rely on metal3-dev-env to set up the bootstrap cluster. It can be even trickier actually, since the code for the e2e tests live in the CAPM3 repo. So to get the latest code for the e2e tests, we need the latest code from CAPM3, but to do an upgrade from an older CAPM3 version we need an older version of CAPM3.

## How to solve this

I'm not sure how we should solve these issues but I think we need to do something to make metal3-dev-env work better with upgrade tests. Here are some suggestions that we could consider:

1. Prepare environment for multiple versions: Use existing images for older releases and build images for the latest code. Create manifests and configuration for both the new and old version. There is nothing preventing us from having a single `metadata.yaml` for both `v1alpha5` and `v1beta1` for example.
2. Identify images with tags so it is easier to spot errors and understand what version they are. This can be the commit sha or some human readable tag like `local-main`, `local-v0.5` or similar.
3. Clarify the interface between metal3-dev-env and other components. Should metal3-dev-env actually deploy CAPM3 or should this be up to the e2e tests in CAPM3?

**Comment by Rozzii** [comment]
NOTE to everybody: Fell free to work on this and contact/ping @lentzi90 if you have any question!

**Comment by lentzi90** [comment]
I suggest closing this as fixed. By adopting the CAPI e2e framework for the upgrade test we managed to "workaround" many of the shortcomings of the dev-env. There are still things that could be improved of course, but the worst is already solved. I also think that it makes more sense to keep the dev-env focused on simulating the baremetal environment, rather than handling all the installation and upgrade scenarios. This is better handled as part of the e2e tests in CAPM3.
