### ISSUE TITLE
Mariadb container usage is unclear

### ISSUE THREAD

**Issue by kashifest** [metal3-io/metal3-dev-env#923]
Since [Baremetal Operator](https://github.com/metal3-io/baremetal-operator/blame/main/tools/run_local_ironic.sh) makes the usage of mariadb false by default, shall we drop any/all code related to mariadb usage from metal3-dev-env or then shall we allow setting the var https://github.com/metal3-io/baremetal-operator/blob/main/tools/run_local_ironic.sh#L93 through some configmap here in metal3-dev-env.

**Comment by kashifest** [comment]
@dtantsur your thoughts would be appreciated.

**Comment by kashifest** [comment]
What about the ironic-deployment in BMO @dtantsur thats still uses mariadb. So our Ubuntu jobs currently dont deploy mariadb containers but centos jobs are using mariadb as a container in ironic pod. Do you have any plane to change that or would it remain as it is?

**Comment by dtantsur** [comment]
I'm working on changes it, but I got lost in ironic-deployment :( I may start asking some questions on Slack at some point. I don't understand e.g. why there is no httpd deployed.

**Comment by Rozzii** [comment]
The question has been answered and it was also discussed on the 02.02.2022 community meeting. As a result of this question Issue #931 has been created.
/close
