### ISSUE TITLE
nordix-airship images (CentOS en Ubuntu) no longer online

### ISSUE THREAD

**Issue by n-able-consulting** [metal3-io/metal3-dev-env#933]
LS,

The to download images (in: lib/images.sh) for CentOs and Ubuntu are no longer online available, so the 01_prepare_host.sh breaks at that point.

Shoutout for your efforts, love this project!

Gr. Ruben Visser

**Comment by n-able-consulting** [comment]
By coincidence found out, their locations changed!
From https://artifactory.nordix.org/artifactory/airship/images/,
To https://artifactory.nordix.org/artifactory/metal3/images/k8s_<kubernetes-version>/
--

**Comment by Rozzii** [comment]
Hi @n-able-consulting, yes currently we are in the process of removing the "airship" references from the metal3 project and as part of that the artifacts have been moved. 
/triage accepted

**Comment by kashifest** [comment]
The images should be available now here https://artifactory.nordix.org/artifactory/metal3/images/k8s. @n-able-consulting please check if its working for you now.

**Comment by n-able-consulting** [comment]
Confirmed working of change!
Thanks for making the effort.
Gr. Ruben

**Comment by furkatgofurov7** [comment]
Thanks for confirming @n-able-consulting!
Closing the ticket, please reopen or create a new one if you hit theis issue again. 

/close
