### ISSUE TITLE
Python3.9 is ignored if other versions are present in the host

### ISSUE THREAD

**Issue by andfasano** [metal3-io/metal3-dev-env#973]
Apparently due the current Ansible setting of `ansible_python_interpreter=auto` configured in [1], python 3.9 will not be selected if in the current host where metal3-dev-env another version is present. 

On rhel8 for example, the debug output shows that `/usr/libexec/platform-python` is used: 
```
$  /usr/libexec/platform-python --version
Python 3.6.8
```

[1] https://github.com/metal3-io/metal3-dev-env/blob/681b4d26ab5f90b0d08679df36b82ebb74eca993/vm-setup/inventory.ini#L2

**Comment by andfasano** [comment]
cc @hardys

**Comment by elfosardo** [comment]
the behavior is actually correct, the "auto" option selects the default python binary for the selected distribution based on a map, which for CentOS-Stream/RHEL 8 is /usr/libexec/platform-python
This is the current map https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1502

**Comment by andfasano** [comment]
Thanks @elfosardo for clarifying that behavior (considering the additional complexity of the ansible debug output that seems to point to 3.9 :) ). I guess we can close then this issue
