### ISSUE TITLE
Installation fails if an older version of kubectl exists previously

### ISSUE THREAD

**Issue by alosadagrande** [metal3-io/metal3-dev-env#98]
I am installing the dev environment on a Centos7 latest. It already had kubectl installed, version 1.5 which is the one available at official repo:
```
[alosadag@smc-master metal3-dev-env]$ rpm -qa | grep kube
kubernetes-client-1.5.2-0.7.git269f928.el7.x86_64

$ yum whatprovides kubectl
kubernetes-client-1.5.2-0.7.git269f928.el7.x86_64 : Kubernetes client tools
Repo        : extras
Matched from:
Filename    : /usr/bin/kubectl
```

Taking into account to 01_prepare_host.sh

```
if ! command -v kubectl 2>/dev/null ; then
    curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/.
fi
```
Kubectl won't be updated to latest version (1.16) which is causing not able to process some yamls via kubectl apply -f.

I would suggest to check version of the kubectl installed as well. In case it is older than latest, update to latest. Take into account that kubectl installed from rpm (at least on CentOS) is placed at /usr/bin/ instead of /usr/local/bin/

**Comment by stbenjam** [comment]
We should determine the minimum version we support, and add a check that it's installed (or handle updating it for the user)

**Comment by alosadagrande** [comment]
PR merged finally, I think it can closed
