### ISSUE TITLE
Proposal: Avoid using dirty repos for deploy 

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/metal3-dev-env#994]
This issue is about how we deploy Ironic and BMO in metal3-dev-env. We currently use the [deploy.sh](https://github.com/metal3-io/baremetal-operator/blob/main/tools/deploy.sh) script and also apply some kustomizations directly after making changes to them (e.g. changing the registry/image/tag).

As seen in #975 it can be problematic to rely on dirty repos. It is hard to know what changes there are, where it is being used and when/how to clean up safely. However, it is obvious that we need to combine the clean manifests with some patches and configuration for specific things in metal3-dev-env. So the question is, can we do this in a better way?

On the one hand it is logical that the knowledge for how to deploy BMO and Ironic lives in the BMO repo. But on the other hand the specifics of the metal3-dev-env cannot come from there. The general solution to this problem when using kustomize, is to create an overlay that adds configuration and patches on top of the base. In our case the base would be the kustomizations in the BMO repo and the overlay could be in metal3-dev-env (some files would probably be temporary, others could be included in version control).

The overlay in metal3-dev-env would be used to override the container images, add secret and configmaps. One thing that makes this more complicated than it sounds is that both BMO and Ironic has multiple different overlays already (e.g. for keepalived, TLS and basic auth). This means that we do not have one single base that we always start from. Instead we need to pick one based on some parameters. We can simplify this a bit by removing some of the options that are less useful (e.g. no auth).

Here is the proposal for what to do in a nut shell:

1. Add a `config` folder in metal3-dev-env that contains kustomizations using BMO/Ironic/CAPM3 as base.
2. Make a temporary `config` folder for example during `02_configure_host.sh`. It would use the `config` folder as a template and add secrets or similar. Clean it up as part of `make clean`.
3. Change `03_launch_mgmt_cluster.sh` so that it uses the temporary `config` instead of cloning and modifying all repos.

Benefits of this:

- The generated config has a logical lifecycle tied to the environment it is used with. (It is generated and cleaned by metal3-dev-env.)
- Metal3-dev-env has ownership over the config needed, so we do not need to add support for everything in BMO just to be able to use it in metal3-dev-env. An example of this in the past would be https://github.com/metal3-io/baremetal-operator/pull/1074.
- Metal3-dev-env does not have to touch files in BMO directly (still depending on the files through kustomizations though).

**Comment by Rozzii** [comment]
@lentzi90 should we leave this issue as stale?

**Comment by lentzi90** [comment]
Yes. I started working on it at some point, but then priorities changed. Maybe at some point I will get back to it.

**Comment by Rozzii** [comment]
@lentzi90 I guess it is still in you backlog so
/remove-lifecycle stale

**Comment by lentzi90** [comment]
Yes, I will comment on this in today's community meeting.

**Comment by Rozzii** [comment]
@lentzi90 do you see a future for this issue ?

**Comment by lentzi90** [comment]
Yes and no. I will still work on simplifying the way we deploy things (especially BMO and Ironic) so that we would not need dirty repos. However, it is not really a dev-env issue so that is why I think we can close this.
